### ISSUE TITLE
many games with ABM make a Bubble will crash with error code C1-2758-2

### ISSUE THREAD

**Issue by dorminirko** [ONElua/AdrenalineBubbleManager#10]
if I use ABM to make a bubbles with PSP/PS1/EMU PBP games
its open with all crash and show error code **C1-2758-2**
what happened?
my PSV is **3.60 Enso with Henkaku R10.2**
Ys Seven is Hanization version crashed
Gunner's Heaven PS1 is original pbp crashed
MVSPSP EMU crashed
prinny2 is original PSP iso either crashed

**Comment by BaltazaR4** [comment]
Is your adrenaline version 6+fix? do this games open and after the boot image go to a black screen for a while and then you get the error? have you tried a different driver setup? please tell us a bit more of what happens :)

**Comment by ONElua** [comment]
"I am getting a C1-2758-2 error when trying to run a game/application" - Your game has not been copied properly and at least one of the file is corrupt, please copy it again and retry.

**Comment by elbie27** [comment]
I have this exact same issue with psx games that ran fine with my own manually added bubbles, using the guide provided by Lman. I had perfectly working bubbles, tried to use this to make a new bubble and now no bubbles for psx games work. I get the exact same error of c1-2785-2 and I have made sure all data is transferred correctly. Multiple times complete with hash checking.
