### ISSUE TITLE
ABM 5.22 and 5.21 do not work correctly with Adrenaline 6.9

### ISSUE THREAD

**Issue by artzox** [ONElua/AdrenalineBubbleManager#100]
- PSVITA model: [1003]
- Version of firmware: [3.65]
- Version of ABM: [5.22]
- Version of Adrenaline: [6.61 build 6.9]

## After installing ABM and creating some bubbles

Obtained result: [bubbles are installed, but do not work as required when adrenaline 
version check is disabled]

## Explain the issue

- [Issue is that if in order for ABM to work as expected the only way is to downgrade adrenaline to version 6.61 - 6.8 build. Disabling the version check in ABM only allows to launch adrenaline from each bubble and not the game itself, which makes ABM redundant.]

**Comment by ONElua** [comment]
In order for bubbles made with ABM to be usable you have to let ABM install adrbblbooter plugins and then disable adrenaline version check and stay in adrenaline v6.8, ABM bubbles relay on adrbblbooter plugins to work

**Comment by artzox** [comment]
Hi OneLua,

thanks for the feedback, but the whole point of me writing this post is to request that compatibility with version 6.9 is enabled, so I can use adrenaline with GTA high res patch and keep using ABM.
ABM works fine with adrenaline 6.8 but the high res patch does not.
