### ISSUE TITLE
Provide working ABM version with Adrenaline 6.9

### ISSUE THREAD

**Issue by artzox** [ONElua/AdrenalineBubbleManager#102]
Hi, 
re-posting this as it was closed without any resolution being provided.
Please register the fact that ABM does not work with version 6.9 and provide a workaround or just say that support will not be provided.
I really like ABM and would like to keep using it, but as is I don't see a solution to use it with GTA high res patch (adrenaline 6.9 needed).

    PSVITA model: [1003]
    Version of firmware: [3.65]
    Version of ABM: [5.22]
    Version of Adrenaline: [6.61 build 6.9]

After installing ABM and creating some bubbles

Obtained result: [bubbles are installed, but do not work as required when adrenaline
version check is disabled]
Explain the issue

    [Issue is that if in order for ABM to work as expected the only way is to downgrade adrenaline to version 6.61 - 6.8 build. Disabling the version check in ABM only allows to launch adrenaline from each bubble and not the game itself, which makes ABM redundant.]

**Comment by ONElua** [comment]
The answer is short...
Until Lman updates their modules (Adrenaline Bubble Booter ), there will be no ABM for adrenaline v6.9

**Comment by ONElua** [comment]
It is not necessary to open more issues on this issue

**Comment by artzox** [comment]
Sorry, didn't understand the issue was not with ABM but the bubble booter.
Thanks for taking the time to reply again.
