### ISSUE TITLE
Manuals do not shows on PSP Bubbles

### ISSUE THREAD

**Issue by sephiroth1993** [ONElua/AdrenalineBubbleManager#103]
- PSVITA model: [PCH-1010]
- Version of firmware: [3.65 Enso]
- Version of ABM: [5.24]
- Version of Adrenaline: [6.9]

## After installing ABM and creating some bubbles

Obtained result: [No manual is showed on PSP Bubble]

## Explain the issue

- When i create a PSP Bubble the manual does not shows on the Livearea, dunno if it's a bug or the manuals are supossed to work only with PS1 games.
  I know the PSP games didn't have digital manuals, but if i have the images and put them in their respective folder, it's not supossed to work anyway?

![2019-05-01-215035](https://user-images.githubusercontent.com/6667667/57161161-3c579800-6dc1-11e9-9d5b-2ef6484ba542.png)

## Extra info

- Reinstaled both adrenaline and ABM, changed the size and format of the manual images.
- sd2vita
- Using tai:config.txt ur0
- Did you add the adrenaline line to tai:config.txt? Of course.
- issue on a specific bubble or all ABM bubbles? Only PSP Bubbles.

**Comment by ONElua** [comment]
ux0:ABM/(Gameid)/Manual/001.png
002.PNG, 003.PNG
(960*544)
![2019-05-03-161019](https://user-images.githubusercontent.com/25811032/57166007-77a49780-6dbe-11e9-9af8-37f7c591cf55.png)

**Comment by ONElua** [comment]
![2019-05-03-161423](https://user-images.githubusercontent.com/25811032/57166132-d66a1100-6dbe-11e9-85c7-d7766cbd8009.png)

**Comment by ONElua** [comment]
Now Manual folder is detected at  !!!! resources injection option !!!!

**Comment by sephiroth1993** [comment]
> 
> 
> Did you do the following?:
> Place the images of your manual in the following path ux0:ABM/(gameid)/Manual/(your images here) if the folders of the mentioned path do not exist then you have to create them, after that inject the images of the Manual with ABM
> 
> https://github.com/ONElua/AdrenalineBubbleManager/blob/master/README.md#inject-images-and-manual-to-abm-bubbles

Thx, the issue was the file format, i was saving it in *.jpg format, now kinda works but the images don't shows, besides the size and format, is there any other setting that i have to adjust, like depth 8bit or something? My images are in formate *.png 24bits., the manual shows "The file is damaged".
