### ISSUE TITLE
attempt to call global 'Extraviados' (a nil value)

### ISSUE THREAD

**Issue by adrianminissale** [ONElua/AdrenalineBubbleManager#104]
- PSVITA model: slim
- Version of firmware: 3.60
- Version of ABM: 5.25
- Version of Adrenaline: 6.9

## After installing ABM and creating some bubbles

- I reinstall adrenaline and abm and restart the psvita
- I use tai:config.txt at ur0
- I add the adrenaline line to tai:config.txt
- I use sd2vita, i see this after install ABM 
![IMG_6522](https://user-images.githubusercontent.com/2480367/57458005-fd08cb80-7246-11e9-87e4-d38e29655f11.jpg)

**Comment by ONElua** [comment]
yup
mi error...
Por favor descargar este archivo corregido
https://github.com/ONElua/AdrenalineBubbleManager/commit/690ea4273de27fe7e144cd651eed9ba9fa99ce64

o simplemente abre el spanish.txt con cualquier editor y en la linea 124 elimina las comillas de más.
Debe quedar asi
"Permite modificar la ruta del juego, solo para juegos marcados como Extraviados"

**Comment by adrianminissale** [comment]
muchas gracias!! ahi funciona.!!!

**Comment by ONElua** [comment]
ok, en breve igual hare el update por este sencillo error :P
