### ISSUE TITLE
ABM Startup Images Resizing

### ISSUE THREAD

**Issue by Asentum** [ONElua/AdrenalineBubbleManager#105]
- Version of firmware: [3.60]
- Version of ABM: [5.62]
- Version of Adrenaline: [6.61]

I have a little over 50 ABM bubbles installed in my live area. All of the pictures I used were injected either by me or from the online directly.

The issue I have pertains to the start up images. Upon boot, the startup images sort of cut off, and you can see the bg0 image sort of bleed into the startup box. I tried tinkering with the size of the images to no avail. Then after launching some applications the images were resized apropriately.

After some testing I've realized that the startup images go back to nornal after launching adrenaline. 

It's worth noting that not all startup images have this issue. I believe games with official startup images are unaltered.

Here are some pictures below. 
http://imgur.com/gallery/CCSlmUD

Thank you for all your work. You make the vita awesome!

**Comment by ONElua** [comment]
add in config.txt ???
*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
