### ISSUE TITLE
Use Filename as Title? 

### ISSUE THREAD

**Issue by Wyverino** [ONElua/AdrenalineBubbleManager#106]
Hello. 
I just wanted to ask whether you could implement a feature to use the filename (minus .iso) as the Title for the bubbles.

Right now I have to correct each games title as most of them appear to be written in caps. 

My files were all renamed on the PC. Is this feature possible? Or is it in the app already and I didnt See it?

**Comment by ONElua** [comment]
in WIP
https://github.com/ONElua/AdrenalineBubbleManager/commit/e4c669d2982c6fed5c543bb0545cdf46c05199e1
