### ISSUE TITLE
Freeze if edit file path on several bubbles at one session

### ISSUE THREAD

**Issue by hometech99** [ONElua/AdrenalineBubbleManager#109]
- PSVITA model: [1000]
- Version of firmware: [3.60 h/e]
- Version of ABM: [3.26]
- Version of Adrenaline: [6.61]

## After installing ABM and creating some bubbles
works

Obtained result: [insert the result you got here]
works
## Explain the issue
I was editing my microSD card and changed some file names.  When put back in the Vita, this obviously will cause some bubble disconnects for those game where bubbles were made
- [What's the issue here]
After I go into  Circle menu of ABM to edit the path of the files for bubbles maybe 2-3 bubbles, the next bubble I edit, when I click X on the path name, total freeze..I have to power down.

## Extra info

- [Have you done anything to try to fix it here]
no
- [sd2vita, psvsd, external storage or omc here]
SD2VITA
- [Using tai:config.txt at ux0, ur0 or both here]
ur0
- [Did you add the adrenaline line to tai:config.txt? here]
yes
- [issue on a specific bubble or all ABM bubbles? here]
n/a...it is editor

**Comment by hometech99** [comment]
what fixed it--posting here--now I just did 5 in a row..no freeze yet...will freeze after I post this comment---watch..

**Comment by hometech99** [comment]
yep---froze after 1 more

**Comment by ONElua** [comment]
you can put the plugins you have installed (ux0 and ur0)

**Comment by ONElua** [comment]
This is plugins problem
or memory
