### ISSUE TITLE
Can you please put function back in to convert bubble pics?

### ISSUE THREAD

**Issue by ajhix36** [ONElua/AdrenalineBubbleManager#11]
Since the 3.6 change, the option to rebuild the pictures has been taken out, because any NEW bubbles will not need it. But now I have 50 bubbles of the old version, it would be much nicer to rebuild and have them convert over, rather than having to reinstall all the bubbles to fix the icons.

**Comment by BaltazaR4** [comment]
That got taken care of on v 3.06, where image convertion was added and the "we need to restart" part of the app got removed, all the bubbles created with v 3.06 or v3.07 will not lose the psp content icons and pics after a db rebuild

**Comment by BaltazaR4** [comment]
oh, I got you now, I think you are right, without the option to restore the bubble it will just look black after the db rebuild, will see if we can do an app to take care of that
