### ISSUE TITLE
Error C1-2758-2 when opening a bubble

### ISSUE THREAD

**Issue by bmn1234** [ONElua/AdrenalineBubbleManager#111]
- PSVITA model: PS TV
- Version of firmware: 3.60
- Version of ABM: 5.30
- Version of Adrenaline: 6.61-6.9

## After installing ABM and creating some bubbles

Obtained result: The bubbles automatically crash and give me the error code listed above

## Explain the issue

The games I installed will not work and keep giving me this error. I have looked far and wide, but no one can either help me, stopped helping me, or gave help but didn't make it clear enough on how to fix the issue (Ex. - Here)

## Extra info

Initially, my Adrenaline games wouldn't work because I didn't have the act.dat, but I downloaded the npm plugin to get them to work properly. 3 of my games are in PBP format, while one is in CSO format.

- I have installed, uninstalled, and reinstalled Adrenaline and ABM multiple times, as well as remove the VSH plugin from the tai folder and the config file.
- sd2vita
- Using tai:config.txt at ur0
- Adrenaline kernel has been added to the tai config 
- Happening on all the ABM bubbles I make.

**Comment by bmn1234** [comment]
Ok, I managed to fix it, with some help from the lovely folks at the HENkaku discord. Firstly, the reason I was getting the Error C1-2758-2 was that on my config.txt, I had listed the adrenaline_kernel.skprx above storagemanager, so if you're getting that issue, check that first to see if that's clashing. Afterward, I was still having trouble loading a game, only now, I was getting the message

### "Could not load adrenaline_kernel.skprx. Please reboot or use the ADRBubbleBooter installer."

After reinstalling both the latest versions of Adrenaline and ABM, I decided to install the **AdrBubbleBooter.VPKEdition v1.1 by Leecherman** on the brewology website. After it installed, I made the bubbles for the games and they loaded perfectly. 

So make sure to install Adrenaline first, get it all set up, then install ABM and have it patch to Adrenaline, then install ABB and patch it into Adrenaline, then when you make the bubbles in ABM, the games should load fine.

**Comment by RamblingShenanigans** [comment]
Just an FYI, I found this because I was getting the same error code when launching a PSP game via the RetroFlow Launcher. I had to reorder my plugin's as well and consolidate 2 separate KERNAL entries I had. Once i did that games launch fine. Thanks for the post!
