### ISSUE TITLE
Doesn't detect Syphon Filter Logan's Shadow

### ISSUE THREAD

**Issue by JarrahWhite** [ONElua/AdrenalineBubbleManager#113]
I have the official PSP classic download from the Australian PSN store downloaded to both my official memory card and my SD2Vita. It simply doesn't show up in the list of games I can create bubbles for. At all. Period. I've even tried redownloading it several times and it doesn't appear.

**Comment by ONElua** [comment]
Install onemenuvita and press on eboot.pbp
show me capture
for example
![2019-07-12-095910](https://user-images.githubusercontent.com/25811032/61137822-d73cb480-a48b-11e9-8cad-31c766dc3773.png)
