### ISSUE TITLE
[Feature Request] Allow Manual only injection

### ISSUE THREAD

**Issue by AnalogMan151** [ONElua/AdrenalineBubbleManager#114]
Currently to inject a manual into a bubble you need to provide at least one of these image files: 

* icon0.png 128x128
* startup.png 280x158 (max)
* pic0.png 960x544
* bg0.png 840x500

in order for the Start button to begin importing. For those of us who already have the bubble the way we want and just want the manual injection, can a manual only option be included?

**Comment by ONElua** [comment]
ok

**Comment by AnalogMan151** [comment]
Tested and worked like a charm. A+ for speed and quality.
