### ISSUE TITLE
PS button problem

### ISSUE THREAD

**Issue by tony9959** [ONElua/AdrenalineBubbleManager#117]
- PSVITA model: [second one]
- Version of firmware: [3.65]
- Version of ABM: [insert version]
- Version of Adrenaline: [insert version]

## After installing ABM and creating some bubbles

Obtained result: [works fine]

## Explain the issue

- [Hi. I just installed your app and it works perfectly. However, I've got some problem about PS button settings. Some kinds of apps like gpsp kai uses PS button as a menu button. When I boot this app into adrenaline, it doesn't have any problem. However, when I boot gpsp kai into the bubble by using your app, PS button opens Adrenaline setting or jump into live area directly so it causes me a problem to open a gpsp menu. Could you please add a settings for PS buttons just like original Adrenaline? (When I press PS button shortly, nothing happens. And If I press long vita menu opens and It could open a Adrenaline settings). ]

## Extra info

- [Have you done anything to try to fix it here]
- [sd2vita, psvsd, external storage or omc here]
- [Using tai:config.txt at ux0, ur0 or both here]
- [Did you add the adrenaline line to tai:config.txt? here]
- [issue on a specific bubble or all ABM bubbles? here]

**Comment by seascape** [comment]
Ah, I just started using ABM (it's amazing!) but also wondered about this. All my PSP plugins are currently tied to PS button combinations and don't seem to work when booted from ABM LiveArea bubbles.

It'd be nice if ABM would let us use the PS button for shortcuts like we can in Adrenaline. Maybe I should change everything to Select in the meantime.

**Comment by BaltazaR4** [comment]
What you guys mentioned are features of Adrenaline Bubble Booter (Lman's plugin), what the ps button in the game is not an Adrenaline Bubbles Manager feature, so, we can not change what it does, since Lman's plugin has only 2 options, which are: going straight to Livearea or opn the Adrenaline menu
