### ISSUE TITLE
ePSP resets in Crazy Taxi

### ISSUE THREAD

**Issue by rboninsegna** [ONElua/AdrenalineBubbleManager#12]
I have noticed that ABM is incompatible with Crazy Taxi Fare Wars (in .cso format, minimum compression) - after Crazy Taxi 1 or 2 is selected (which loads the game in .prx format from the iso, may be related?) the screen turns black for a second, then the usual "Sony Computer Entertainment" appears and XMB is shown, fully functional (any game can be selected, including Crazy Taxi again, and it will not have this issue; same as if Adrenaline was launched directly)

Inferno+eboot.pbp mode, Adrenaline 6-fix, Enso, sd2vita on ux0

Thanks for looking into this and for all the other games I have which work just fine!

**Comment by ONElua** [comment]
have you tried a different driver setup?
try ....
M33
BOOT.BIN

**Comment by BaltazaR4** [comment]
you can either try m33+eboot.old or np9660+boot.bin

**Comment by rboninsegna** [comment]
Thanks! Working fine with NP9660 (what I normally use on a real PSP) and EBOOT!
