### ISSUE TITLE
Error x080010016  failed to install 

### ISSUE THREAD

**Issue by manofsteel2017** [ONElua/AdrenalineBubbleManager#120]
- PSVITA model: [insert model]2000
- Version of firmware: [insert version]365
- Version of ABM: [insert version]?
- Version of Adrenaline: [insert version]661

## After installing ABM and creating some bubbles

Obtained result: [insert the result you got here]

## Explain the issue
Latest vitashell too I'm getting x080010016
And I'm not sure why. 
Thanks. I'm sure this is no longer supported or something

**Comment by ONElua** [comment]
Try with onemenu.

**Comment by manofsteel2017** [comment]
> Try with onemenu.

What's that?vitashell alternative?

**Comment by ONElua** [comment]
https://github.com/ONElua/ONEMenu-for-PSVita/releases/tag/3.16

**Comment by manofsteel2017** [comment]
Thanks.
It still failed. 
I guess it's my SD card. 
Eveyrhing else installed

**Comment by BaltazaR4** [comment]
How many bubbles you have in livearea?

**Comment by manofsteel2017** [comment]
> How many bubbles you have in livearea?

Like a lot. I downloaded like 40 games

**Comment by ONElua** [comment]
> Thanks.
> It still failed.
> I guess it's my SD card.
> Eveyrhing else installed

Close
