### ISSUE TITLE
Memory card manager

### ISSUE THREAD

**Issue by RexNihil** [ONElua/AdrenalineBubbleManager#121]
- PSVITA model: [2001]
- Version of firmware: [Enso 3.60]
- Version of ABM: [6.11]
- Version of Adrenaline: [6.61 v6.9]

## After installing ABM and creating some bubbles

Obtained result: [Bubbles start as they ought]

## Explain the issue

- [Starting Memory Card Utility through Adrenaline Menu>Open Official Settings>Memory Card Utility results in "cannot access the virtual memory card" error.]

## Extra info

- [Have found no solution]
- [sd2vita]
- [Using tai:config.txt at ur0]
- [Did you add the adrenaline line to tai:config.txt? yes]
- [All Bubbles]

**Comment by BaltazaR4** [comment]
This issue has nothing to do with Adrenaline Bubbles Manager, it is related to Lman's plugin.

**Comment by RexNihil** [comment]
> This issue has nothing to do with Adrenaline Bubbles Manager, it is related to Lman's plugin.
Which one? Lman has several.

**Comment by RexNihil** [comment]
> This issue has nothing to do with Adrenaline Bubbles Manager, it is related to Lman's plugin.

If you mean adrbblbooter.suprx, I don't have that on my system, or at least not in my tai folder. If you mean another plugin, which one?

**Comment by RexNihil** [comment]
I've looked in the pspemucfw folder in app and appmeta, in ux0 and ur0, and didn't find Lman's plugin anywhere...because I've never used it. I installed both Adrenaline and ABM through vpks obtained from the respective git pages. 

Nowhere in either of those (that I saw) did it require me to install Lman's plugin, or even recommend it. Although there's a brief mention of that plugin on ONElua's Git page for ABM, that's all it is: 

"Adrenaline Bubbles Manager (ABM) purpose is to create the bubbles and necesary links to boot chosen psp iso/cso/pbp files with adrenaline v6.x through Lman's plugin adrbblbooter".

So...am I receiving this error when opening a game through an ABM-created bubble because I don't have a plugin that nothing I've seen says is essential to the process? Or is your statement that it's not related to ABM incorrect? I do not understand.

**Comment by BaltazaR4** [comment]
Like I said, this issue is related to adrenaline bubble booter plugin which is needed to do this: "boot chosen psp iso/cso/pbp files with adrenaline v6.x through Lman's plugin adrbblbooter" Lman's plugin is not installed to folder tai, cause it goes directly to PSPEMUCFW folder and ABM tells you its going to install it right at the first time you open our app if you don't have it, cause its required.

**Comment by RexNihil** [comment]
What it appears I'm not adequately explaining is that I do not have a plugin called adrbblbooter in any of the three PSPEMUCFW folders on my device. 1 in ur0: appmeta, 1 in ux 0: app, 1 in ux: 0 appmeta. None of them contain that plugin. No ABM folder on my device contains that plugin. No where on my device will you find that plugin.

ABM works. The bubbles created by it all work, each and every one. Without that plugin being on my system. Or in the tai.config, which I saw somewhere it needed to be, in the kernel section.

I do not have that plugin. And everything still works. With the glaring exception of the Memory card manager, which is the entire reason I opened this issue in the first place. I'm really not trying to be rude, but you insist the issue lies with a plugin I do not have and was never asked to install in the first place. Is there some fork app called Adrenaline Bubbles Manager version 6.11 R2019 Team ONElua - ONElua.x10.mx? Because if there is, please tell me, and I'll go bother them about it.

**Comment by BaltazaR4** [comment]
Lman's plugin replaces the original adrenaline plugins inside PSPEMUCFW

**Comment by BaltazaR4** [comment]
I wasn't trying to be rude either, but ABM tells you it installed Lman's plugins the very first time you use it and it replaces adrenaline original plugins and adds adrbblbooter to PSPEMUCFW cause Lman's plugins are required to boot psp content from bubbles created with ABM
![2020-05-03-171551](https://user-images.githubusercontent.com/29612219/80926039-2a089500-8d5a-11ea-991b-b60beb09ee22.jpg)
![2020-05-03-171359](https://user-images.githubusercontent.com/29612219/80926040-2b39c200-8d5a-11ea-87f4-574175ad5750.jpg)

**Comment by ONElua** [comment]
Fix memory card https://github.com/ONElua/AdrenalineBubbleManager/commit/c2ea46ac0821cc0c8e1a7781b323d7ea16d32726
