### ISSUE TITLE
Where can I upload bubbles for others?

### ISSUE THREAD

**Issue by MoonshineIndustries** [ONElua/AdrenalineBubbleManager#122]
I see online resources but only for download. I did the 3 psp prince of persia games but not sure where to upload them. Going to do Tomb Raider next.

**Comment by DevDavisNunez** [comment]
You can share them here or do a direct pull to the corresponding files, https://github.com/ONElua/VitaBubbles#to-share-resources-images

**Comment by MoonshineIndustries** [comment]
I don't know how to make the pull request so here they are.

https://drive.google.com/drive/folders/1rZzl8naQFcVQc9qig3yPN6C6hTkYBi8w?usp=sharing

**Comment by ONElua** [comment]
okay
Thank you

In a few days they will be online

**Comment by MoonshineIndustries** [comment]
Thank you.

**Comment by MoonshineIndustries** [comment]
I updated the startup.png of the three titles so the start button is not over them and put the preview.jpg where they should be. Hopefully you didn't upload them yet.

They're in the same link from above. Thanks
