### ISSUE TITLE
seplugins don't load when launched through Bubble (Project Diva Extend English patch)

### ISSUE THREAD

**Issue by MarioMover** [ONElua/AdrenalineBubbleManager#123]
- PSVITA model: [Slim]
- Version of firmware: [3.60]
- Version of ABM: [6.1.2]
- Version of Adrenaline: [6.9]

## After installing ABM and creating some bubbles

Games load fine and work fine. No issues there.

## Explain the issue

Seplugins just don't load. Specifically, the Project Diva Extend English patch. It loads fine when launched through the Adrenaline menu, but the game launches in Japanese without the patch when launched through the bubble.

## Extra info

- Game installed on uma0:/memory stick
- tai:config.txt at ur0:
- Line added
- Issue so far is specific but only because I have just one game/patch to test

**Comment by ONElua** [comment]
Try
https://github.com/ONElua/AdrenalineBubbleManager/issues/123
