### ISSUE TITLE
Adrenaline not booting after update

### ISSUE THREAD

**Issue by Purplstuph** [ONElua/AdrenalineBubbleManager#125]
- PSVITA model: 1000
- Version of firmware: 3.60
- Version of ABM: 6.12
- Version of Adrenaline:6.61
## After installing ABM and creating some bubbles

Obtained result: error c1-2858-3 for adrenaline

## Explain the issue

- after updating ABM and clicking on a new bubble, i get error c1-2858-3. Figuring this was just one bubble, i go check adrenaline only to get the same error. It wasn't like that before.

## Extra info

- I've reverted back to ABM 6.11 and everything is fine.
- Using sd2vita as ux0

**Comment by ONElua** [comment]
Maybe plugin conflict

**Comment by BaltazaR4** [comment]
Please try installing Adrenaline Bubbles Manager to its newest version, and update gepatch plugin
