### ISSUE TITLE
we need an update for the new version of adrenaline 7.0

### ISSUE THREAD

**Issue by Fershock** [ONElua/AdrenalineBubbleManager#126]
The flow has updated adrenaline and bubble manager downgrades that version. @ONElua team, could you create an update? Thanks in advance

**Comment by Saix13** [comment]
Agreed. We really need an update so we can use the new adrenaline but still use bubbles. Is there any plan on doing this?

**Comment by ONElua** [comment]
Yes... waiting for lman Plugins adrenaline booter
