### ISSUE TITLE
How to uninstall ABM?

### ISSUE THREAD

**Issue by dizine** [ONElua/AdrenalineBubbleManager#127]
- PSVITA model: N/A
- Version of firmware: 3.60
- Version of ABM: 6.12
- Version of Adrenaline: 6.9

- I have ABM installed (App and Adrenaline) but want to uninstall now. I can delete app/bubbles etc but can’t find any info/instructions re: completely uninstalling ABM and revert to unmodified Adrenaline.

Is there an uninstall option?
What does ABM install and where (can these files be manually deleted)?
Do I need to uninstall Adrenaline to remove ABM?

Thanks for your help.

**Comment by ONElua** [comment]
only uninstall ABM and ABM Bubbles

In adrenaline go to Update system for updating to adrenaline v7
[image: 2020-09-24-222730-792763.png]

**Comment by dizine** [comment]
1. Delete ABM app and any bubbles created/installed from Vita Home Screen
2. Delete ux0:ABM
3. Delete ux0:data/ABM
4. See ‘How to install’ https://github.com/TheOfficialFloW/Adrenaline#how-to-install and follow instructions for fresh installation.
