### ISSUE TITLE
ABM Version 6.13

### ISSUE THREAD

**Issue by Saix13** [ONElua/AdrenalineBubbleManager#128]
On the main github for ABM it lists the following:

Changelog 6.13
Adrenaline Bubble Booter v1.3 Compatibility By LMAN 'leecherman'
Adrenaline v7.0 Compatibility By LMAN 'leecherman'

I cannot seem to locate 6.13 for download. I also tried booting up ABM on my Vita and it does not prompt me to update.

My apologies if I am overlooking something simpe.

**Comment by ONElua** [comment]
Tomorrow

**Comment by Saix13** [comment]
> Tomorrow

OK thank you :)

I look forward to the new version.
