### ISSUE TITLE
Ys: The Oath in Felghana cannot be played by ABM

### ISSUE THREAD

**Issue by Ted-bissada** [ONElua/AdrenalineBubbleManager#129]
PS Vita 1000
3.60
ABM 6.13
Adrenaline V7

Errors out with error c1-2858-3

i can open and play the game via normal adrenaline but when opening 
it with ABM it hangs on black screen and eventually errors out

I have tried all the separate drivers and enabling disabling high-memory and plugins none of it seems to make a difference 
all other bubbles i have work normally and i am on a sd2vita with the adrenaline open 2 times fix in my config.txt

this is not really a big deal but im posting it here for posterity

**Comment by ONElua** [comment]
For me working!!!

![2020-11-06-171907-127391](https://user-images.githubusercontent.com/25811032/98423458-43193800-2054-11eb-9b73-df11a8942a81.png)

**Comment by Ted-bissada** [comment]
Ty for help I changed execute to boot.bin and its working now i did not think to test that i thought it was for homebrew stuff
