### ISSUE TITLE
Please add imc0 support to ABM

### ISSUE THREAD

**Issue by vatomalo** [ONElua/AdrenalineBubbleManager#13]
if files.exists("imc0:") then
        scan.isos("imc0:pspemu/ISO")
        scan.pbps("imc0:pspemu/PSP/GAME")

And(with some help from XYZ and MPT and vita hacking discord)

	val=5
	
	if src.path:sub(1,2) !="um" and src.path:sub(1,2) !="im" then val=4 end
	local path2game = src.path:gsub(src.path:sub(1,val).."pspemu/", "ms0:/")

**Comment by ONElua** [comment]
yes....
next version!!!
thks
