### ISSUE TITLE
[Feature Request] Configurable Plugins

### ISSUE THREAD

**Issue by NeonLightning** [ONElua/AdrenalineBubbleManager#130]
I was wonder if there would be a way to make ABB able to have adjustable plugin settings beyond just all on and all off? mostly useful for gepatch and being able to just turn it on with games that it works on. as holding L at game boot doesn't work.

**Comment by BaltazaR4** [comment]
Try holding button up + L + R at the same time when booting the psp/psx bubble to disable gepatch

**Comment by ONElua** [comment]
![2020-12-29-202005-107211](https://user-images.githubusercontent.com/25811032/103326687-25929a00-4a17-11eb-88e5-cef497206215.png)
Bubble Settings -> Edit boot.bin
