### ISSUE TITLE
Pop up update

### ISSUE THREAD

**Issue by Enabl3r** [ONElua/AdrenalineBubbleManager#131]
When the pop up for updating comes up, whether I accept the update or not it forces a restart and downgrades adrenaline back to 6.9. Repeated process and same result

**Comment by ONElua** [comment]
Please send me your folder sce_module
from ux0:app/PSPEMUCFW/sce_module

**Comment by googlytturdman** [comment]
[sce_module.zip](https://github.com/ONElua/AdrenalineBubbleManager/files/5787675/sce_module.zip)

**Comment by ONElua** [comment]
Ofw? Sd2vita?

**Comment by Enabl3r** [comment]
Enso 360 and yes

**Comment by BaltazaR4** [comment]
What's the Adrenaline Bubbles Manager version giving you this issue?

**Comment by Enabl3r** [comment]
It's the one directly previous to the current version. When I went into it it would say that there is an update available and whether I accepted it or not It would say I needed to reboot then I would open up adrenaline and it would have been downgraded to v6.9

**Comment by ONElua** [comment]
please send me app/ADRBUBMAN

**Comment by Enabl3r** [comment]
I've manually updated it now :/ haven't had any problems since. I'll try and replicate it tomorrow and let you know how I get on.

**Comment by Enabl3r** [comment]
I've accidentally deleted the previous version. If you would like me to try and replicate it send me the last 2 previous versions and ill get on it

**Comment by BaltazaR4** [comment]
This gets fix installing iTLSfull package by SKGleba
