### ISSUE TITLE
Entering official PSP/PSX settings crashes adrenaline

### ISSUE THREAD

**Issue by knerlington** [ONElua/AdrenalineBubbleManager#132]
- PSVITA model: Slim
- Version of firmware: 3.60
- Version of ABM: Latest as of this writing
- Version of Adrenaline: 7.0

## After installing ABM and creating some bubbles

Obtained result: Bubbles work and boot just fine

## Explain the issue

- Problem is that entering the official PS1 or PSP settings from the adrenaline overlay crashes adrenaline.
- Before installing and using ABM it worked just fine. Now it also crashes if I enter adrenaline (booting the PSP system) without ABM at all and try to enter the official settings.

## Extra info

- Using sd2vita set as ux0
- Adrenaline line added to tai:config.txt

**Comment by ONElua** [comment]
Show me your plugins in ur0:tai/config.txt

**Comment by knerlington** [comment]
Just found the issue; I had the reRescaler plugin installed as well which replaces the original rescaler for PSVITA. Was under the impression this was used for native PSVITA titles only, but obviously it's the one used for PSP and PSX games. Removing this fixed the issue.
