### ISSUE TITLE
CPU clock value problem

### ISSUE THREAD

**Issue by SirJonatanLopez** [ONElua/AdrenalineBubbleManager#133]
- PSVITA model: [Fat]
- Version of firmware: [3.65]
- Version of ABM: [6.14]
- Version of Adrenaline: [7.0]

## After installing ABM and creating some bubbles

Obtained result: [Bubbles boot fine]

## Explain the issue

- On adrenaline  XMB, when you press Select button and change "CPU CLOCK GAME", the value you set here doesn't match with the value on Recovery Menu / CPU Speed. On Adrenaline clean install without ABM the issue isn't present.

## Extra info
-Sd2Vita

**Comment by ONElua** [comment]
The settled speed does not shows at recovery, only at vsh menu, talking to Lman about this issue.
