### ISSUE TITLE
Audio bug after loading save state or returning from sleep mode

### ISSUE THREAD

**Issue by rkiller3x6** [ONElua/AdrenalineBubbleManager#134]
- PSVITA model: PSV 1006
- Version of firmware: h-encore 2 3.65 spoofed to 3.73
- Version of ABM: 6.14
- Version of Adrenaline: 7

## After installing ABM and creating some bubbles

Obtained result: [Bubble works fine]

## Explain the issue

Hi, I'm experiencing audio issues after loading save state or returning from sleep mode. I've played The Warriors and Corpse Party thru ABM and experience complete audio distortion. I'm not entirely sure if it affects other games as well but I really want help to fix this. 

## Extra info
Using sd2vita on ux:0
config.txt running on ur:0

**Comment by ONElua** [comment]
Try in adrenaline

**Comment by ONElua** [comment]
This bug is for Adrenaline
