### ISSUE TITLE
Bubbles stop working and give 'error has occurred. (C0-8977-1)'

### ISSUE THREAD

**Issue by ljewe7** [ONElua/AdrenalineBubbleManager#135]
- PSVITA model: [2000]
- Version of firmware: [3.60 Enso]
- Version of ABM: [6.14]
- Version of Adrenaline: [7]

## After installing ABM and creating some bubbles

Obtained result: [All work initially but then some fail to start with 'error has occurred. (C0-8977-1) message]

## Explain the issue

Hi, I'm having an weird issue whereby PS1 eBoots I've turned into bubbles using Adrenaline Bubble Manager stop launching with an 'error has occurred. (C0-8977-1) message (I have tried google that but didn't find a good answer). The bubbles are fine when first created - but at some point the error occurs. When I go back into ABM, they appear as if uninstalled again in the list.

This causes a tricky problem - if I delete the non-functional bubble from Live-Area that deletes the whole game file and save from my system! - and I can't remove the bubble using ABM because for whatever reason ABM no longer thinks there is a bubble. Catch 22! Please help.

## Extra info

- [Have you done anything to try to fix it]:
 - The only way I can get my game/s back to functioning is: Backup my saves using Vitashell; delete the game/s affected using Live-Area edit-mode; restart; go back into ABM were now the game doesn't appear at all on the list - even as uninstalled; close that; then reinstall my PS1 eBoots and saves; restart; go into ABM an recreate installed bubbles!

Blimey - but guess what - It's not worth doing that because in a couple of days or after a reboot it does it again!

- [sd2vita]
- [Using tai:config.txt at ur0]
- [Did you add the adrenaline line to tai:config.txt? - Yes]
- [issue on a specific bubble or all ABM bubbles?] Currently the problematic games showing the error are: Tempest X3, Vanark, Micro Machines v3, Alien Trilogy, Doom and Final Doom (about a third of my PS1 titles... but until I sort this problem I'm sure they won't be the last ones)'

A couple of notes: this doesn't happen to all PS1 games, but I think it may be happening to the same ones repeatedly - I think!

All my game eBoots are backups of PS1 titles I actually own either physical or digitally - they are installed from my PSN Store download-list files. They are separate eBoot files that I keep safe on my computer and side-load using Vitashell USB. This is because I like to give my PS1 games custom graphics using ABM, and if I do that with PSN shop downloads you get a duplicate bubble, plus with the store going soon down I'd rather use safe-backups and side-load.

**Comment by ONElua** [comment]
what plugins are you using in ur0: tai/config.txt
and pspsemu/seplugins/game.txt

**Comment by ljewe7** [comment]
Hello and thank you so much for looking into this. Also my apology for
being slow to get back to you.


*So here is my ur0: tai/config.txt:*
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.

*KERNEL
ur0:tai/storagemgr.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/0syscall6.skprx
ur0:tai/reVita.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/PSVshell.skprx
ur0:tai/ioplus.skprx

*main
ur0:tai/henkaku.suprx
ur0:tai/shellbat.suprx
ur0:tai/pngshot.suprx
ur0:tai/download_enabler.suprx
ur0:tai/nolockscreen.suprx
ur0:tai/quickmenuplus.suprx
ur0:tai/reVitaMotion.suprx

*NPXS10015
ur0:tai/henkaku.suprx

*NPXS10016
ur0:tai/henkaku.suprx
*ALL
ur0:tai/VitaGrafix.suprx

*and pspemu/seplugins/game.txt:*

There is no file in here!! It's a completely empty folder.

**Comment by katawajojo** [comment]
Has anything ever come of this? I'm running into the same issue on the latest ABM on a 1000 series.

**Comment by ONElua** [comment]
> Has anything ever come of this? I'm running into the same issue on the latest ABM on a 1000 series.
> 
> Update: This seems to be specifically an issue with me for POPS titles. Anything downloaded via PSN or NPS works fine, but anything made via PSX2PSP has this issue.
> 
> Update 2: I think I've narrowed down the issue, although I'm not 100% certain of the cause. If the game is a PSP game, PSP ISO, or PSX game from PSN or NPS, using GameID for the bubble name works fine. However, if the game is a PSX2PSP eboot, the bubble will fail to start after a few restarts. The workaround for this is to make those custom PSX games with bubble IDs using "PSPEMUXXX".
> 
> I'm not sure if this is due to a way the Vita validates license files, since PSX2PSP doesn't create a KEYS.BIN anymore, so I can't verify if it's that is the cause. The Vita might be verifying any licenses with AppIDs starting with:
> 
> ```
> SCES
> SCED
> SLES
> SLED
> SCUS
> SLUS
> SCPS
> SLPS
> SLPM
> ```
> 
> The error given is usually saying that the application requires a system update, iirc.

Install npdrmfree plugin

**Comment by katawajojo** [comment]
npdrmfree is required for NPS... so that's not the issue here. I've already verified that's not the problem.
