### ISSUE TITLE
boot.png image partially warped/glitched in corner 

### ISSUE THREAD

**Issue by ducky1psn** [ONElua/AdrenalineBubbleManager#136]
- PSVITA model: 1000
- Version of firmware: 3.60 Enso
- Version of ABM: 6.14
- Version of Adrenaline: 6.61 - 7
## After installing ABM and creating some bubbles

Obtained result: Bubbles look fine and load fine

## Explain the issue

- When using a custom boot.png image, the top and top right corner of all images used for the boot.png are glitched/warped out: https://ibb.co/YBYwXmj and https://ibb.co/HD3svW3 
- It appears like the image is being scrunched up in the corner, marked with the red box. This happens with the recommended resolution (480x272), as well as any other resolution, it happens with any image used, and it happens in every game boot.png.
- I've only tested on PS1 games, not PSP

## Extra info

- [Have you done anything to try to fix it here]
- I tested with different images/resolutions, deleted bubbles and remade them 

- [sd2vita, psvsd, external storage or omc here]
- using sd2vita and Official Sony memory card

- [Using tai:config.txt at ux0, ur0 or both here]
- using tai:config.txt at ur0

- [Did you add the adrenaline line to tai:config.txt? here]]
- Yes

- [issue on a specific bubble or all ABM bubbles? here]
- Tested only on PS1 games

**Comment by seriouslyunderappreciated** [comment]
Can confirm, haven't found a way around this.

**Comment by ONElua** [comment]
Please share me your boots.png

**Comment by BaltazaR4** [comment]
Please zip the images you are using and share them here, or at least a link, so we can download and check them to see if there is something wrong with them

**Comment by Minolito** [comment]
I have the same issue as well, the boot.png is "teared" at the top and especially the top right corner.

https://ibb.co/x5T27XW
https://ibb.co/GCKs9YY
https://ibb.co/CmSfYFD

This problem seems to appear:

-With both psp and psx games
-With the boot.png  resized and with the palette reduced beforehand
-With ABM automatic conversion


I have attached a zip with 3 boots.png that have the same issue, one original psp PIC1 (perfect size), a resized image, a image that will have to be resized with ABM.

[boot.zip](https://github.com/ONElua/AdrenalineBubbleManager/files/7171649/boot.zip)

**Comment by ONElua** [comment]
@Minolito You help me check something, in an already created bubble, manually place your boot.png in the app/ pspemu.../data
480x272 32-bit or 8-bit

**Comment by Minolito** [comment]
@ONElua I tried it with multiple already created bubbles and images. It seems that only the 480x272 32-bit boots.png are correctly displayed.

**Comment by ONElua** [comment]
Try
https://www.dropbox.com/s/4005qx42ldr56vp/AdrenalineBubbleManager.vpk?dl=0

**Comment by Minolito** [comment]
With this version it works correctly, no more distorsion in top right corner of the boot.png !

I tried it with both already existing and new bubbles.

**Comment by ONElua** [comment]
https://github.com/ONElua/AdrenalineBubbleManager/commit/14cac24ed984285ef1ec156589f8e2f384e21af1
