### ISSUE TITLE
Bubble Manager keeps Crashing when creating bubbles

### ISSUE THREAD

**Issue by Thenuke1** [ONElua/AdrenalineBubbleManager#137]
- PSVITA model: 2k
- Version of firmware: 3.65
- Version of ABM: 6.14
- Version of Adrenaline: 7
## After installing ABM and creating some bubbles
issue happens when making bubbles

Obtained result: [insert the result you got here]

## Explain the issue
app crashes when i select multiple bubbles anywhere from 3 - 8 sometimes it creates all 8 sometimes it only loads the title of the bubble and then when it gets ready for the next title it crashes

- when it crashes psvita either freezes and only hard reset will shut it down or error c2-12828-1 pops up with this line
- ux0:data/psp2core-1626987843-0x0000c62a3b-eboot.bin.psp2dmp

## Extra info
using bubble manager for psp psx and emulators from psp

- ive tried googling and searching and cant seem to find anyone else with the issue
- [sd2vita
- [Using tai:config.txt at ur0, deleted ux0
- [Did you add the adrenaline line to tai:config.txt? here]
- [issue on a specific bubble or all ABM bubbles? here]

**Comment by BaltazaR4** [comment]
Hello, can you mention please any of the titles you are trying to create bubbles for, or a specific title that this happened with? Are you adding custom resources? A corrupted image in one of my ISOs was making the app crash, maybe this is the same case
