### ISSUE TITLE
Can't create bubbles for some PBP games

### ISSUE THREAD

**Issue by mpostermann** [ONElua/AdrenalineBubbleManager#138]
- PSVITA model: PCH-1101
- Version of firmware: 3.65 Henkaku Enso
- Version of ABM: 6.16
- Version of Adrenaline: 7

## After installing ABM ~~and creating some bubbles~~

Obtained result: Some of my purchased PSP games did not appear in the list of games to make bubbles for

## Explain the issue

The app fails to detect certain PSP games that I legally purchased from the Japanese Playstation Store. Of the 7 games I own, 5 fail to load. I did some debugging and I believe the issue is located in the [scan.insertPBP function](https://github.com/ONElua/AdrenalineBubbleManager/blob/master/AdrenalineBubbleManager/system/scan.lua#L83).

The reason the games don't load is due to the sceid check that starts on line 97:
```
local sceid = game.sceid(string.format("%s__sce_ebootpbp",files.nofile(hand.path)))
if sceid and sceid != "---" and sceid != hand.name then
	_insert=false--nothing
end
```

I added a custom_msg call at line 98 and confirmed that the name of the game folder does not match the sceid that gets loaded:
```
custom_msg(string.format("do not insert %s; sceid is %s", hand.name, sceid))
```
![Log Message](https://user-images.githubusercontent.com/82477657/179671294-e6078386-30e6-40f7-bb2e-011f47a16b1a.jpg)

The underlying issue is that these games all had multiple releases with different IDs. The ID that gets loaded from the `game.sceid()` call seems to be the "final" release (such as an Ultimate Hits version) while the versions I have are from a previous version. You can look the various IDs up from here: https://psxdatacenter.com/psp/ntsc-j_list.html.

Here's a list of all the games that fail to load (all Japanese titles):
|Game|Folder Name|game.sceid()|
| -- | --------- | --- |
|Tales of Phantasia - Narikiri Dungeon X|ULJS00293|NPJH50848|
|Tales of Destiny 2|ULJS00097|NPJH50850|
|Tales of Rebirth|ULJS00132|NPJH50851|
|Tales of Eternia|ULJS00015|NPJH50853|
|Tactics Ogre – Unmei no Wa|ULJM05753|NPJH50348|

## Extra info

- Have you done anything to try to fix it?: I commented out the check in lines 97-99 and I was able to create bubbles for my games successfully. I'm not sure if there's any side effects of skipping that check though.
- Using omc
- Using tai:config.txt at ur0
- Did you add the adrenaline line to tai:config.txt?: Yes
- Issue on a specific bubble or all ABM bubbles?: Specific bubbles, listed above

**Comment by ONElua** [comment]
Pelease try
https://github.com/ONElua/AdrenalineBubbleManager/blob/master/AdrenalineBubbleManager/system/scan.lua#L98

-- _insert=false--nothing

**Comment by mpostermann** [comment]
Thanks, I tried that and that worked for me.
