### ISSUE TITLE
Error in installing a bubble for a certain homebrew.

### ISSUE THREAD

**Issue by azumukupoe** [ONElua/AdrenalineBubbleManager#14]
I can't install a bubble for Cave Story.
Please help me if this is not a bug.

**Comment by ONElua** [comment]
which is the error ?
Please send me capture or link from Homebrew....

**Comment by ONElua** [comment]
ok..the problem is the PIC1.PNG
try with this...
https://www.dropbox.com/s/77exe9uewrc0ihj/cavestoryRC1.zip?dl=0

**Comment by azumukupoe** [comment]
It worked like a charm!

thx
