### ISSUE TITLE
idea: trasparent bubble background

### ISSUE THREAD

**Issue by jirikrepl** [ONElua/AdrenalineBubbleManager#140]
Hello,
would it be possible to add trasparent bubble background? Same as ps vita folders have

**Comment by ONElua** [comment]
In bg0?

**Comment by jirikrepl** [comment]
Sorry, I don't understand, you mean that bg0 could be the color name? Now there's 19 colors `Colors (0)` ... `Colors (18)`

Is it even possible to create a bubble with transparent background?
I mean it could look like a ps vita folder, just with the psp/psx icon inside

**Comment by BaltazaR4** [comment]
Hello, we try making transparent bubbles when chosing the colors that would be included, but, whenever a bubble with transparencies was installed, it will become black
