### ISSUE TITLE
Bubbles don't work fully

### ISSUE THREAD

**Issue by kazum1kun** [ONElua/AdrenalineBubbleManager#142]
- PSVITA model: Slim
- Version of firmware: 3.65
- Version of ABM: 6.17
- Version of Adrenaline: 7

## After installing ABM and creating some bubbles

Obtained result: the game (Ys I & II) launches normally, and I can get to the main menu. I then select Ys I, and the game crashes in middle of the loading screen. The emulator then resets/reboots.

Similar results for Ao no Kiseki, where I can get to the main menu, and upon starting a new game the emulator errors out (C1-2858-3).

## Explain the issue

- The game should launch and run normally. This error does not occur when I launch the games inside Adrenaline.

## Extra info

- [Have you done anything to try to fix it here]
I tried changing a few launch parameters, such as using BOOT.BIN instead of EBOOT.BIN, disable forced high memory layout, etc

- [sd2vita, psvsd, external storage or omc here]
sd2vita
- [Using tai:config.txt at ux0, ur0 or both here]
ur0
- [Did you add the adrenaline line to tai:config.txt? here]
yes, I also have NoDrmFree on adrenaline 
- [issue on a specific bubble or all ABM bubbles? here]
Apparently the issue can happen on other titles

**Comment by ONElua** [comment]
Change the driver

**Comment by kazum1kun** [comment]
Wow, dumb me tried everything but this most obvious option haha. Can confirm March33 driver fixes this issue.
