### ISSUE TITLE
Launching ABM (post-install) causes GPU crash

### ISSUE THREAD

**Issue by alog243** [ONElua/AdrenalineBubbleManager#143]
- PSVITA model: 2000 (slim - gundam special edition)
- Version of firmware: enso 3.65 (via VitaDeploy easy upgrade)
- Version of ABM: 6.17 (latest)
- Version of Adrenaline: Adrenaline-7 6.61 (latest)

## After installing ABM and verifying Adrenaline XMB still works

Obtained result: Installed ABM, ran ABM first time (no errors), rebooted, verified Adrenaline XMB + games
Every time I run ABM, I get this error/crash:
"GPU Driver detects GPU Crash. Generating CoreDump: [*********]"

## Explain the issue

- ABM will not run :(

## Extra info

- Tried rebooting - same issue every time it launches. Did not try reinstalling or removing plugins
- using sd2vita + YAMT
- ur0:/tai/config.txt
- "ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx" is in my config.txt

**Comment by ONElua** [comment]
Please share your config.txt

**Comment by alog243** [comment]
Sorry - a bit new to this. Here's ur0:tai/config.txt

```
# YAMT
*NPXS10015
ur0:tai/yamt.suprx
*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/yamt_helper.skprx

# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
ur0:tai/0syscall6.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/repatch.skprx
ur0:tai/PSVshell.skprx
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

# Optional QoL plugins
*KERNEL
# removes brightness and wifi restrictions for games
ur0:tai/NoPowerLimits.skprx
# increases max/decreases min brightness, disabled by default
# ur0:tai/vitabright.skprx
*main
# shows battery percentage near the gauge
ur0:tai/shellbat.suprx
# screenshots are png instead of jpg
ur0:tai/pngshot.suprx

```

I did a bit of searching yesterday for Vita GPU crashes and tried commenting out pngshot and NoPowerLimits, but that didn't have any effect, so I uncommented those lines again.

I originally modded my Vita like 3 years ago back when gamesd was the sd2vita method, and updated to YAMT just this weekend, so I'm guessing I just have some plugins that I need to remove. But I'm not sure which ones are necessary.

**Comment by BaltazaR4** [comment]
When you start ABM and it crashes, is it getting to the part where start searching for games? Or it's crashing before that?

**Comment by alog243** [comment]
I see a few log lines as it's starting up (after the ONElua splash), but it's too fast to read. It instantly crashes before getting to any other screen.

**Comment by BaltazaR4** [comment]
This issue might be caused by a corrupted icon in one of your games, try recording after starting ABM during the log lines to see on which game name it crashes

**Comment by alog243** [comment]
Here's the full log before the GPU crash:
```
Loading C/ISO ux0:pspemu/ISO/ULUS10308.iso
Loading C/ISO ux0:pspemu/ISO/ULUS10297.iso
Loading C/ISO ux0:pspemu/ISO/ULUS10512.iso
Loading PBP ux0:pspemu/PSP/GAME/NPUJ00067/EBOOT.PBP
Loading PBP ux0:pspemu/PSP/GAME/NPUJ01041/EBOOT.PBP
Loading PBP ux0:pspemu/PSP/GAME/NPUJ94221/EBOOT.PBP
Loading PBP ux0:pspemu/PSP/GAME/NPUJ00900/EBOOT.PBP

<crash>

GPU Driver detects GPU Crash.
Generating CoreDump: [                   ]
```

**Comment by alog243** [comment]
I also have the .psp2dmp core dump files, but don't have the tools or know-how to parse them.

**Comment by ONElua** [comment]
https://www.dropbox.com/s/cuuzv2lg4lx77xu/AdrenalineBubbleManager.vpk?dl=0

**Comment by alog243** [comment]
That one didn't crash

logABM.txt:
```
Loading C/ISO ux0:pspemu/ISO/ULUS10308.iso
Loading C/ISO ux0:pspemu/ISO/ULUS10297.iso
Loading C/ISO ux0:pspemu/ISO/ULUS10512.iso
Loading PBP ux0:pspemu/PSP/GAME/NPUJ00067/EBOOT.PBP
Loading PBP ux0:pspemu/PSP/GAME/NPUJ01041/EBOOT.PBP
Loading PBP ux0:pspemu/PSP/GAME/NPUJ94221/EBOOT.PBP
Loading PBP ux0:pspemu/PSP/GAME/NPUJ00900/EBOOT.PBP
Loading PBP Scan Finish
Loading PBP Shows Games
Loading PBP Load 1st PIC
Loading PBP Load icon0: ux0:pspemu/iso/ulus10308.iso
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj01041/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj94221/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj00067/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/iso/ulus10297.iso
Loading PBP Load icon0: ux0:pspemu/iso/ulus10512.iso
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj00900/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/iso/ulus10512.iso
Loading PBP Load icon0: ux0:pspemu/iso/ulus10297.iso
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj00067/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj94221/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/psp/game/npuj01041/eboot.pbp
Loading PBP Load icon0: ux0:pspemu/iso/ulus10308.iso
```

It properly booted into the menu, listed my games etc.
I didn't try doing anything yet.

**Comment by ONElua** [comment]
Testing and testing xD

**Comment by alog243** [comment]
Was that package based on the same code as the v6.17 release?
Also, should I try reinstalling v6.17 in case my installation was messed up somehow?

**Comment by ONElua** [comment]
Yes v6.17 with debug

**Comment by alog243** [comment]
Reinstalling fixed it ...
Well, sorry for the waste of time xd
Is there anything else you want me to check before closing this?

**Comment by ONElua** [comment]
No

**Comment by alog243** [comment]
Alright then - thanks for the quick turnaround. Glad it turned out to be nothing.
Cheers
