### ISSUE TITLE
I want to share custom bubble icons i created and also some i found online from others that aren’t yet in the repository.

### ISSUE THREAD

**Issue by Ichigo7s** [ONElua/AdrenalineBubbleManager#144]
- PSVITA model: [insert model]
- Version of firmware: [insert version]
- Version of ABM: [insert version]
- Version of Adrenaline: [insert version]

## After installing ABM and creating some bubbles

Obtained result: [insert the result you got here]

## Explain the issue

- [What's the issue here]

## Extra info

- [Have you done anything to try to fix it here]
- [sd2vita, psvsd, external storage or omc here]
- [Using tai:config.txt at ux0, ur0 or both here]
- [Did you add the adrenaline line to tai:config.txt? here]
- [issue on a specific bubble or all ABM bubbles? here]

**Comment by Ichigo7s** [comment]
I didn’t exactly get the instructions detailed here on the site, so would it be okay to just leave the download links here?

**Comment by ONElua** [comment]
Yes
40 custom bubbles

**Comment by Ichigo7s** [comment]
Thank you, one more now lol it’s 41. This is my custom set:
https://drive.google.com/file/d/1-m0WBiCzp7WwElh-HaA_QMc1xlx7g2Vl/view?usp=drivesdk

And these are from other guys, but that aren’t yet in the online repository, as i compared and checked:

By TeknoRider: https://drive.google.com/drive/mobile/folders/1caXmrvyGjDZAO5vDzwy8nyKNKFpHAAAr?usp=sharing

By LeonardStrife90:
https://drive.google.com/drive/mobile/folders/1_7g3MbMyuaI9LN3zsfbotaa3YUY22_Db?usp=sharing

By maki_mioda:
https://drive.google.com/drive/mobile/folders/1g9A_DCNUyXDTwbR9SMz1dd9cUhkBKg80?usp=sharing

By seraf5:
https://drive.google.com/file/d/1cNITVtcZVgRaiwH4r2PPNYZby509uso8/view

Persona Bubbles by Drazini:
https://drive.google.com/drive/mobile/folders/1JIGrwK-sMf1jx8hYEiHJsIfyy4QzjnFr?usp=drive_open

By Diegorocha2007:
https://drive.google.com/drive/mobile/folders/1OlOI7ba7PkA4ua6dluvRu4f3LfTXHqSM

**Comment by Ichigo7s** [comment]
These are a lot of to add and surely would take a lot of time/work to add, so would understand If you can’t add them all. But someday these links will be taken down and the custom bubbles be gone, as it happened already to a few other sets and the users don’t seem to be much active anymore to reupload. Would be sad if they are gone forever, as there is nice work done here by many.

**Comment by ONElua** [comment]
https://github.com/ONElua/VitaBubbles/commit/05302e88452925f4f12f7974de8167fab5053ff4
So they are bubbles.zip
json is not necessary

**Comment by Ichigo7s** [comment]
So am i to upload the rest? I understood the file names part and setting the preview picture for the bubble, but where/how do i upload the files?

**Comment by BaltazaR4** [comment]
You can find some instructions on how to share them here https://github.com/ONElua/VitaBubbles#to-share-resources-images

**Comment by Ichigo7s** [comment]
As i wrote in my first comment, i didn’t get those completely, not used to Github, so don’t know where to make upload requests and do i need to do a new request for each single game or is it possible to bundle them?

**Comment by ONElua** [comment]
Dont problem
Im upload some custom bubbles from here
https://drive.google.com/file/d/1-m0WBiCzp7WwElh-HaA_QMc1xlx7g2Vl/view?usp=drivesdk

**Comment by ONElua** [comment]
https://github.com/ONElua/VitaBubbles/commit/9776401fc6620da5cd5c8d74a258200122407a9d

![2023-02-12-141704-601900](https://user-images.githubusercontent.com/25811032/218335062-15843f4e-98db-44b6-b72e-e53ef0ba8289.png)

**Comment by Ichigo7s** [comment]
Thank you so much :)

**Comment by Ichigo7s** [comment]
Hi,

i made some new Bubbles, could you maybe update my list and add these new ones to them if you find the time? Would really appreciate it 🙏

Here is the link for the new bubbles i made:

https://drive.google.com/file/d/1FvBb9LPGffrJRGGUpR-aj3KOqkaQV7Ig/view?usp=drivesdk

**Comment by ONElua** [comment]
> Hi,
> 
> i made some new Bubbles, could you maybe update my list and add these new ones to them if you find the time? Would really appreciate it 🙏
> 
> Here is the link for the new bubbles i made:
> 
> https://drive.google.com/file/d/1FvBb9LPGffrJRGGUpR-aj3KOqkaQV7Ig/view?usp=drivesdk

https://github.com/ONElua/VitaBubbles/commit/a5682030b3cea31dc89af611feb18eec0ed73428
