### ISSUE TITLE
[Feature Request] Auto-add DOCUMENT.DAT if it exists

### ISSUE THREAD

**Issue by endervad** [ONElua/AdrenalineBubbleManager#147]
If you store PSP/PSX games as EBOOT.PBP (either extracted from PSN PKG, or bought and downloaded from PSN), there's a DOCUMENT.DAT file that corresponds to the game's manual. It would be nice if ABM could detect existence of this manual and inject it automatically to LiveArea without a need to move the manual to PC, convert it to PNGs, and transfer them back to Vita.

**Comment by ONElua** [comment]
For PSP
https://github.com/qwikrazor87/pspdoc/releases
