### ISSUE TITLE
Bubble manger wont open

### ISSUE THREAD

**Issue by Brg1222** [ONElua/AdrenalineBubbleManager#149]
- PSVITA model: 1000
- Version of firmware: 3.65
- Version of ABM: 6.19
- Version of Adrenaline: 6.61

## After installing ABM and creating some bubbles

Obtained result: unable to create bubbles

 [What's the issue here] 
![IMG_7245](https://github.com/ONElua/AdrenalineBubbleManager/assets/140037830/51e9d853-0b0b-45a3-92fb-623e3f8eb26b)

## Extra info. I have been able to create bubbles fine until recently i can only get the screen i attached a photo of above. Adrenaline works fine, its just the bubble manager thats not opening.

- [Have you done anything to try to fix it here] checked vita shell and all files are there. 
- [sd2vita, psvsd, external storage or omc here]
- [Using tai:config.txt at ux0, ur0 or both here]
- [Did you add the adrenaline line to tai:config.txt? here]
- [issue on a specific bubble or all ABM bubbles? here]

**Comment by ONElua** [comment]
When starting abm or by creating a bubble? Do you have abm bubbles created with abm old versions?

**Comment by Brg1222** [comment]
Yes i believe so. Definitely have bubbles created with older version

**Comment by Brg1222** [comment]
> When starting abm or by creating a bubble? Do you have abm bubbles created with abm old versions?

And i get that screen as soon as i start ABM

**Comment by ONElua** [comment]
Try to remove all abm bubbles from livearea

**Comment by Brg1222** [comment]
> Try to remove all abm bubbles from livearea

How do i do this without losing my games?

**Comment by ONElua** [comment]
Wait
replace the file Inside ux0:app/ADRBUBMAN/system 

https://www.dropbox.com/scl/fi/55y3pr7xj1yo803d9mevm/bubbles.lua?rlkey=94rhuaonkebzkjtp3w2dir97h&dl=0

**Comment by Brg1222** [comment]
Awesome! I replaced the file and it’s working! I can create bubbles again, thank you so much. When i start ABM i get this and when i click x, the bubble manager starts up and seems to be working correctly. As long as that’s normal i think im good to go and I appreciate your help! Let me know if that message i put the picture of is normal. And thanks again 
![IMG_7314](https://github.com/ONElua/AdrenalineBubbleManager/assets/140037830/3f419ead-f201-4010-aee5-e23c0464b45c)

**Comment by ONElua** [comment]
Ok
I need update for this fix.
