### ISSUE TITLE
An error has occurred. 

### ISSUE THREAD

**Issue by ajhix36** [ONElua/AdrenalineBubbleManager#15]
I can not install more than 30 games. I instantly get a crash when I try to make another.

Also when mass installing if you try to do 10 or more, when it gets to the 10th your vita will hard lock.

**Comment by BaltazaR4** [comment]
Working on it, btw, what seems to be a hard lock, is only a ps button lockup to prevent exiting ABM when is doing the install process, but power button can be normally used

**Comment by ajhix36** [comment]
You are right about the hard lock, it does still let me power off when that happens.

**Comment by ONElua** [comment]
Fixed issue which prevented installing more than 30 bubbles...
OSK not opening at the 10th bubble when doing multi-install will probably get fixed adding a custom keyboard (w.i.p.)
