### ISSUE TITLE
Adrenaline bubbles crashing with C1-2858-3 error after installing Persona 2 Eternal Punishment with English translation fan patch using ABM

### ISSUE THREAD

**Issue by DENemezis** [ONElua/AdrenalineBubbleManager#150]
- PSVITA model: 2000
- Version of firmware: 3.65 CFW
- Version of ABM: 6.19
- Version of Adrenaline: 7.0

## After installing ABM and creating some bubbles

Obtained result: Persona 2 Eternal Punishment (with English translation fan patch) crashes with C1-2858-3 and makes all the other adrenaline bubbles crash with the same error. 

## Explain the issue

- Persona 2 Eternal Punishment, which was added to the system using the adrenaline bubble manager, is causing crashes with error code C1-2858-3. Additionally, all other adrenaline bubbles installed on the system are also crashing with the same error when attempting to launch the game. It's worth noting that this issue is occurring even though an English translation fan patch has been applied to the game.

## Extra info

- Some weird side effect since the last update is that **all** of the startup.jpgs on all Adrenaline games have been squeezed by 20% from the top. After running a game from the bubbles or the adrenaline app itself it reverts to normal. Unsure if it is related to this issue but I think it is worth mentioning. 
- All games work perfectly fine unless I start that Persona 2 game
- I can fix the issue somewhat by disabling the patches for  [remastered controls](https://github.com/TheOfficialFloW/RemasteredControls/releases) the ones that I am using are for GTA LCS/VCS

**Comment by BaltazaR4** [comment]
Hello.
Everytime you get the error C1-2858-3 on any game the ps vita needs to be rebooted so the other games/apps can be launched again, the error itself is not ABM related, but, have you tried changing boot mode for this bubble? Is there any psp plugins enabled? If the answer is yes, have you tried disabling them.

**Comment by ONElua** [comment]
There is two options:
Uninstall gta_native.prx plugin directly from adrenaline.
Or within abm, edit the bibble and disable plugins for this bubble
![Uploading 2023-07-20-191000-080822.png…]()

**Comment by DENemezis** [comment]
> There is two options: Uninstall gta_native.prx plugin directly from adrenaline. Or within abm, edit the bubble and disable plugins for this bubble
> 
> ![2023-07-20-191000-080822](https://user-images.githubusercontent.com/25811032/255049359-a3bb12bc-7245-4c25-8d42-77096ad27360.png)

I apologise for the tardiness in my reply but I had some issues. 

I solved the issue by doing as you said - disabling the patches for Persona 2 did the trick.
