### ISSUE TITLE
Bubble created but no thumbnail image was proposed

### ISSUE THREAD

**Issue by y0LAs** [ONElua/AdrenalineBubbleManager#151]
- PSVITA model: PCH-1004
- Version of firmware: 3.65
- Version of ABM: 6.20
- Version of Adrenaline: 6.61

## After installing ABM and creating some bubbles

Obtained result: Bubble created but without icon (Rollcage - SLUS00800)

## Explain the issue

- I created my own .pbp file from multiple .bin files for this game, it works fine, but ABM didn't propose any thumbnail, am I missing something?

This is my first attempt and I didn't try with any other game yet.

## Extra info

- [Have you done anything to try to fix it here]
No
- [sd2vita, psvsd, external storage or omc here]
SD2Vita, 512Go card
- [Using tai:config.txt at ux0, ur0 or both here]
ux0 only.
- [Did you add the adrenaline line to tai:config.txt? here]
No
- [issue on a specific bubble or all ABM bubbles? here]
Didn't try any other one yet.

**Comment by ONElua** [comment]
And on adrenaline?

**Comment by y0LAs** [comment]
The game shows up but without any image either (the same solid blue color)
It has the PS1 border though.

**Comment by ONElua** [comment]
Show me

**Comment by ONElua** [comment]
You will have to add a valid image for your icon0
https://www.dropbox.com/s/hve7e479chxfqvt/Pics.7z?dl=1

**Comment by y0LAs** [comment]
![20231111_015217](https://github.com/ONElua/AdrenalineBubbleManager/assets/15331126/efa2484f-7cf2-4520-8edb-44aad9ac4a0b)
The other PSP and PS1 games have icons, but were obtained with PKGj.
I don't know where the icon0 folder is on the PS Vita, and on the folder you shared, Rollcage USA SLUS00800 isn't there.

**Comment by y0LAs** [comment]
In case you wanted to see it on Adrenaline :
![20231111_023722](https://github.com/ONElua/AdrenalineBubbleManager/assets/15331126/2c9415ba-6dca-4f17-a873-fd204b1395b7)
Other games downloaded with PKGj are fine :
![20231111_023729](https://github.com/ONElua/AdrenalineBubbleManager/assets/15331126/8f4ae224-3e38-4880-8638-11f28b52c492)
I checked on AdrenalineDocs and they don't have any of the Rollcage games, maybe it's related?

**Comment by ONElua** [comment]
The problem is your eboot. You need to add icon0.png, pic0,pic1,etc with psx2psp

**Comment by y0LAs** [comment]
Thank you very much, I'll do that!
