### ISSUE TITLE
Valkyria Chronicles II boots from Adrenaline, but not from bubble (C1-2858-3)

### ISSUE THREAD

**Issue by RazzeeX** [ONElua/AdrenalineBubbleManager#152]
- PSVITA model: [VTE-1006]
- Version of firmware: [3.65]
- Version of ABM: [6.20]
- Version of Adrenaline: [v.7, FW 6.61]

## After installing ABM and creating some bubbles

Obtained result: [C1-2858-3 with [ULUS-10515](https://cdromance.org/psp/valkyria-chronicles-ii-usa/)]

## Explain the issue

- I used to had this issue with other games as well, but now only with Valkyria Chronicles II.
- Game boots normally from Adrenaline, but from bubble it goes to a black screen and then C1-2858-3.
- Video displaying normal boot, bubble behavior and config.txt: https://www.youtube.com/watch?v=ILZARgwnL1E 

## Extra info

- [I tried reinstalling all relevant homebrew, such as Adrenaline, Adrenaline Bubble Manager. Remade the bubbles too.]
- [I use SD2Vita mounted as uma0 in YAMT]
- [Only inside ur0]
- [Yes, I did after reading this line and rebooted the system]
- [Valkyria Chronicles II's (ULUS-10515 at CDRomance) bubble only]

**Comment by ONElua** [comment]
@RazzeeX
Undub?

You have yamt
What do you use gamesd.skprx ?

**Comment by RazzeeX** [comment]
Yes, the UnDUB version. By default they show both unpatched and patched copies.

I have YAMT driver enabled and set up this way:
- ux0: SD2Vita
- uma0: Internal Storage.

About gamesd.skyprx, I honestly do not remember of installing it in the first place. Probably came with Ensõ or another homebrew when I unlocked the PS TV years ago. In any case, it is not being loaded by config.txt.

I can play Valkyria Chronicles III just fine from the bubble, as any other game, but Valkyria Vhronicles II for some reason, despite being in the same storage, can only be loaded from Adrenaline. I already deleted the ISO and put it back.

**Comment by ONElua** [comment]
Change
Execute to BOOT.BIN

In settings bubbles with triangle

**Comment by RazzeeX** [comment]
Yes! Selecting boot.bin made it work. Thanks.

Why is that, though? Adrenaline Bubble Manger boots from eboot.bin by default, while Adrenaline boots from boot.bin?

Would you recommend settings all bubbles to boot.bin or just the only ones that have issues?

**Comment by ONElua** [comment]
eboot.bin by default 
Some games you have to try

**Comment by RazzeeX** [comment]
Hi!

I ripped all my PSOne games using my PS3, and converted them to Eboots.

All games work properly. However, one such exception is "Twins Story", a visual novel.

The game runs properly from the bubble, but once I close the PSPemu window, the PS Vita TV itself freezes.

This is the only game that causes this, but it runs normally from Adrenaline.

Do you have any idea what may be the cause?

**Comment by ONElua** [comment]
No, sorry
Try another driver
