### ISSUE TITLE
iso folder scan issue?

### ISSUE THREAD

**Issue by Yeahhbuddy** [ONElua/AdrenalineBubbleManager#155]
- PSVITA model: 2001
- Version of firmware: 3.65
- Version of ABM: 6.20
- Version of Adrenaline: 6.61

Hello, I have this problem where when I load up ABM after a fresh installation and it reads my psp iso list normally then stops on a game that had a corrupted iso file. So I deleted the corrupted iso file then went through every single psp iso in adrenaline to make sure nothing else was corrupted. I then went back to ABM in it scans like normal then proceeds to stop on the corrupted iso even though it is no longer on my sd card. I tried uninstalling and reinstalling using the methods listed [here](https://github.com/ONElua/AdrenalineBubbleManager/issues/127) and still have the same results. I also searched up to see if anybody had the same problem and it seems that someone had the corrupted iso problem but not the problem of being stuck on the loop of reading an old version of the same iso folder?? If anybody has any suggestions it would be greatly appreciated.

- [Have you done anything to try to fix it here] uninstalled and reinstalled multiple times and researched the problem extensively 
- [sd2vita, psvsd, external storage or omc here] sd2vita
- [Using tai:config.txt at ux0, ur0 or both here] ur0
- [Did you add the adrenaline line to tai:config.txt? here] Yes
- [issue on a specific bubble or all ABM bubbles? here] All

**Comment by ONElua** [comment]
Are you sure it's just an iso?

**Comment by Yeahhbuddy** [comment]
> Are you sure it's just an iso?

I can't say for sure but another person had a similar issue where it would scan the iso folder and stop on a corrupted iso. After deleting the iso his seemed to work fine. It seems that mine is doing something similar although the ISO it's scanning is no longer on the device. It's been completely erased. So then it now leads me to believe that the ABM is stuck on a loop scanning an old version of the same iso folder. Sorry if this doesn't really make sense. If you have any suggestions that would be greatly appreciated. If it comes down to it I'll just reset everything but I'd rather try and fix it first.

**Comment by ONElua** [comment]
First make sure it is the same iso. You may have more corrupt isos

**Comment by Yeahhbuddy** [comment]
> First make sure it is the same iso. You may have more corrupt isos

I don't have the ISO anymore of that game. And I went through every ISO on adrenaline and none of them were corrupted.

**Comment by Yeahhbuddy** [comment]
![unnamed](https://github.com/user-attachments/assets/ede7df3c-5fe8-4507-a37d-13277e2155a5)
This is what's happening. It just stops on an ISO thats not there.

**Comment by ONElua** [comment]
Show ISO folder

**Comment by Yeahhbuddy** [comment]
![unnamed](https://github.com/user-attachments/assets/309d3544-0f8d-4f0e-b189-60f68491a415)
![1](https://github.com/user-attachments/assets/4e512d29-668f-40ce-8990-3e4a3fae73c5)
![2](https://github.com/user-attachments/assets/3b5de32c-5cd2-44b6-9b51-dfb24cfbb89c)
![3](https://github.com/user-attachments/assets/0cb5a41b-5d95-4dfe-8dab-235e66efe2ee)
![4](https://github.com/user-attachments/assets/ec6ab27c-c4cc-4d4c-b712-ae6e7d503bea)
![5](https://github.com/user-attachments/assets/5017f880-3e5b-4d54-9851-9cc1a23dd547)

**Comment by Yeahhbuddy** [comment]
if you need anymore photos please let me know

**Comment by Yeahhbuddy** [comment]
Sorry turns out the corrupted ISO was still in my pspemu folder. I deleted it and everything worked as it should. Thanks for the response.
