### ISSUE TITLE
Mhz not at 333 even though it's set in Adrenalin?

### ISSUE THREAD

**Issue by Zeitwaechter** [ONElua/AdrenalineBubbleManager#16]
Hi there!
Thanks for developing this application! 👍 

I might have missed something but I experience the issue that ISOs, which are started through Bubbles, are not executed/run at full speed.
When I return from those games to Adrenalin (via Home-Button) and start the same ISO again, it runs at 333MHz - like expected.
As I found no similiar issue I decided to create a new one.

I use ABM 3.09 but will redo/-install the games with 3.10 in ~30 minutes.
Furthermore, Adrenalin 6-fix is in usage.

If I could provide anymore useful information to you please don't hesitate to ask me to do so.

Greetings :)

**Comment by BaltazaR4** [comment]
Hi, can you mention a couple of games please?

**Comment by ONElua** [comment]
Adrenaline Bubbles Manager (ABM) purpose is to create the bubbles and necesary links to boot chosen psp iso/cso/pbp files with adrenaline v6.x through Lman's plugin adrbblbooter, all done within the ps vita, but, ABM does not change cpu speed or drivers behavior, any issue related with that should be mentioned to theflow or Lman

**Comment by Zeitwaechter** [comment]
Hey there!

@ONElua :
Thank you for your fast reply! 👍 
I will close this issue for now and will seek an answer for this on TheFlows' part first. 

@BaltazaR4 :
You can see this behaviour specifically with DBZ Tenkaichi Tag Team as it states the following after executing: "The clock frequency for the PSP(rights) (PlayStation(rights) Portable) system in use is 222 MHz. Multiplayer performs better at 333 MHz clock frequency".
Run it as bubble, the message will appear. Run it from Adrenaline itself and it won't.

Hope I could help any other person looking for the same problem even though it's not answered right now. Anyways, it might point in the right direction.
I might be posting any new development in this issue.

Greetings :)
