### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by 1upus** [ONElua/AdrenalineBubbleManager#17]
Can you fix Cyrillic chars width and make external langpack (like vitashell) to make translations?
![img_3359](https://user-images.githubusercontent.com/21283299/31816788-494766e8-b59a-11e7-94fb-69165cf6e328.JPG)

**Comment by ONElua** [comment]
Please...
Send me your translation.

**Comment by ONElua** [comment]
Please... use v4.01 and try this font
https://www.dropbox.com/s/n9sl4exiy4rpk0n/font.ttf?dl=0

**Comment by 1upus** [comment]
Thx! v.4.01 looks better with new font, but system messages still uses original font.
Also, can we translate "System Message" "Quit" etc?..
![img_3367](https://user-images.githubusercontent.com/21283299/31850100-b35f1d80-b655-11e7-858b-863cf02fd4cb.jpg)

**Comment by ONElua** [comment]
well... 
Its necessary to make a complete os.messagebox (custom...)
but maybe it's later

**Comment by 1upus** [comment]
You did it! :) It looks much better. Now only updater strings is missing...
Also I'm use modded Roboto font with PS Buttons glyphs (Can be downloaded from my repo).
![img_3378](https://user-images.githubusercontent.com/21283299/31879084-dce3c9c2-b7e4-11e7-8c5f-f3ca1c5d2d3a.jpg)

**Comment by ONElua** [comment]
your font is missing japanese chars :(
well...thks for the report

**Comment by 1upus** [comment]
It was deleted to reduce font size.
Modded font with PS Buttons glyphs and full UTF charsets can be downloaded here:
https://github.com/1upus/psv_translations/tree/master/AdrenalineBubbleManager_RU/MS_YaHei_full_PSmod
