### ISSUE TITLE
French language and one issue

### ISSUE THREAD

**Issue by chronoss09** [ONElua/AdrenalineBubbleManager#19]
ABM crash when there are no PSP game

and this is a French language if needed : 
https://mega.nz/#!35V2XQAQ!IqKR2_7EXcIf8l1KV3e_uX_5Qs-tvby9e-kUV6hb61c

**Comment by ONElua** [comment]
thks for the translation :+1: 

Im fix more bugs...
please replace scan.lua
https://www.dropbox.com/s/s2oy7r68xuenfsn/scan.zip?dl=0

**Comment by chronoss09** [comment]
Can't translate the latest version, my file isn't changing the langue for the installer...
