### ISSUE TITLE
Error with psp bubble homebrew creation

### ISSUE THREAD

**Issue by 1upus** [ONElua/AdrenalineBubbleManager#20]
I have error when I'm trying to install bubble for homebrews:
https://sites.google.com/site/cavestorypsp/cavestory-psp-rc1.zip
http://www.cavestory.org/downloads/cavestory_cfw_rus_1.0.7z
But it perfectly works with adrenaline.

**Comment by ONElua** [comment]
https://github.com/ONElua/AdrenalineBubbleManager/issues/14
https://twitter.com/gdljjrod/status/917776575189233664
