### ISSUE TITLE
Script Lang.lua

### ISSUE THREAD

**Issue by chronoss09** [ONElua/AdrenalineBubbleManager#21]
Can't translate the latest version, my file isn't changing the langue for the installer...

**Comment by ONElua** [comment]
Translate new system/lang.lua and put in the path
"ux0:data/ABM/lang.lua"

**Comment by chronoss09** [comment]
Thanks it work but scan.lua have another problem, i've no psp game but when i press R, I got an error...

**Comment by azumukupoe** [comment]
I get garbled texts with Japanese

**Comment by ONElua** [comment]
eyyy...
C'mon
https://github.com/ONElua/AdrenalineBubbleManager/issues/19

**Comment by chronoss09** [comment]
ok thanks

**Comment by ONElua** [comment]
re-download...
