### ISSUE TITLE
Font for translations

### ISSUE THREAD

**Issue by 1upus** [ONElua/AdrenalineBubbleManager#22]
Hi, I'm found ttf font similar to original and fix Cyrillic glyphs width. It has JP chars to. Also PS buttons glyphs was added. (link: https://github.com/1upus/psv_translations/tree/master/AdrenalineBubbleManager_RU/font_NewRodin_Pro_B_cyrfix%2B )

**Comment by ONElua** [comment]
thanks for your font, but I think something was edited wrong cause the width gave me problems...
