### ISSUE TITLE
Question about .otf font support

### ISSUE THREAD

**Issue by 1upus** [ONElua/AdrenalineBubbleManager#24]
Hi, your Lua interpreter perfectly works with ttf fonts, but, have it otf suport?
In my project I'm tryed to load font from sa0:data/font/pvf/ltn0.pvf (as we know .pvf it's .otf fonts) but text was invisible after it. 

Also can I use more that one font? First for text output, and second for special symbols, like PS buttons?

THX

**Comment by ONElua** [comment]
at this moment that font is not supported in onelua... only pgf and ttf.
we maybe will add it in the next update....

**Comment by 1upus** [comment]
👍

**Comment by ONElua** [comment]
please..send me DM in twitter

**Comment by 1upus** [comment]
I have not Twitter:/
Can you email me? anbarsukov (at) gmail (dot) com
