### ISSUE TITLE
Error c2-12828-1

### ISSUE THREAD

**Issue by Einst0ne** [ONElua/AdrenalineBubbleManager#25]
I instaled successfuly 166 bubles, but noticed that after install more than 100, it sometimes give error c2-12828-1...

Now after having created 166, I cannot create any more bubbles, it always gave error c2-12828-1 when I press X button.
The error occur before loading the keyboard to put the game name...

I'm a developer without any knowledge of how PS Vita/TV works... but let me know if you need any help.

Thank you

**Comment by ONElua** [comment]
sorry..send me DM in twitter.

**Comment by ONElua** [comment]
please try v4.06...

**Comment by Einst0ne** [comment]
It worked fine without any issues.

Thank you! :)
