### ISSUE TITLE
Error C1-2758-2 when opening a bubble

### ISSUE THREAD

**Issue by afdc98** [ONElua/AdrenalineBubbleManager#28]
Hi, I'm using version 4.06 and sd2vita (I don't have an official memory card inserted). I have Adrenaline-6 fix and I don't have a previous installation of Lman's plugin. I don't know what could be causing this, but I'm pretty sure I followed the instructions correctly.

Btw, when I press OK on the error screen it just loops indefinitely.

**Comment by ONElua** [comment]
Try
reinstall adrenaline and check that it works...

**Comment by afdc98** [comment]
I fixed it by changing the adrenaline_kernel.skprx in my ur0:tai folder copying it again from the Adrenaline app folder and replacing the old one. I didn't know the installer modified all the plugins inside the folder sce_module in the Adrenaline app folder, so on boot my PSVita was loading the old one in ur0:tai instead of the modified new one.

**Comment by ONElua** [comment]
It is necessary to replace the plugins in sce_module, because we use plugins from LMAN
https://sites.google.com/site/theleecherman/adrbubblebooter/vpkedition

**Comment by Majdoubi-Abdessamad** [comment]
bza3at
