### ISSUE TITLE
error c1-2758-2

### ISSUE THREAD

**Issue by millenius** [ONElua/AdrenalineBubbleManager#29]
Hi I installed a theme through TEMA after neglecting to do so for a week or so of setting up my new PSTV, and immediately afterward I started a PSX game (through bubble of course, specifically soul reaver) and it worked okay 
but then I closed the game and the livearea was acting super sluggish so I rebooted the PSTV system via henkaku settings -> reboot system.

After that the livearea was snappy again, but all **230** or so previously working bubbles I created through ABM 4.07 throw the error c1-2758-2 I tried rebooting a few times to no avail, and rebuilding the database is about the worst thing I can imagine (360 bubbles in my livearea, separated by system & alphabetized in folders - took several tedious hours) 

PSVita games are still perfectly fine.
Edit: I should have said, adrenaline is also working fine, the ABMbubbles are all that is broken.

So at this point in writing, I tried creating some new bubbles for a few games with the new v4.08 and those still throw the error and crash...

Is there anything to try or is rebuilding the database pretty much it at this point?

**Comment by BaltazaR4** [comment]
try with the VPK Easy Power Refresh from Onelua, with the option update db, this will refresh the db without losing the bubble layout

**Comment by millenius** [comment]
Thanks for the reply

I tried that and still having the same problem :/

**Comment by ONElua** [comment]
https://github.com/ONElua/AdrenalineBubbleManager/issues/28#issuecomment-352577671

**Comment by BaltazaR4** [comment]
did you try reinstalling adrenaline and adrenaline bubble booter plugins? this fixed the same error for somebody else
