### ISSUE TITLE
"Cancel" when creating the bubble

### ISSUE THREAD

**Issue by Fortesqu3** [ONElua/AdrenalineBubbleManager#31]
Would be nice if once you press X to create a bubble, in the screen of "Name of the bubble" you can cancel with CIRCLE and get back normally. Instead, it goes on and creates the bubble.

**Comment by ONElua** [comment]
The best way to cancel if you have marked many bubbles is press PS when the keyboard is open to put the name of the bubble. And so exit of the ABM
