### ISSUE TITLE
Error c1-2858-3 with Tenkaichi Tag Team

### ISSUE THREAD

**Issue by Lordjontan** [ONElua/AdrenalineBubbleManager#33]
I have installed the app on 3.65 and it works well with all games except for one game (Tenkaichi Tag team). When I open the bubble get a black screen and few seconds later error c1-2858-3, but the game works flawless when is open directly  from Adrenaline

**Comment by ONElua** [comment]
try another driver or execute eboot.bin

**Comment by Lordjontan** [comment]
try both, still not works. I try also with both iso/cso and still not works

**Comment by ONElua** [comment]
for me work....my iso is clean

**Comment by Lordjontan** [comment]
It's the USA version (ulus10537). I'll try with another iso and let you know

**Comment by ONElua** [comment]
me too... (emuparadise) :P
