### ISSUE TITLE
X/O flip on japanese vitas

### ISSUE THREAD

**Issue by dude22072** [ONElua/AdrenalineBubbleManager#34]
Even on Vitas where O is select and X is back AdrenalineBubbleManager still uses the western configuration.

**Comment by azumukupoe** [comment]
Asia too

**Comment by ONElua** [comment]
sendme DM in twitter

**Comment by dude22072** [comment]
@ONElua What twitter would that be?

**Comment by DavisDev** [comment]
Hello @dude22072 
Please send a message to member Gdljjrod!
https://twitter.com/gdljjrod

**Comment by ONElua** [comment]
please try...
https://www.dropbox.com/s/61xw2a0e7h6eitp/AdrenalineBubbleManager.vpk?dl=0

**Comment by dude22072** [comment]
Twitter user Gdljjrod has their DMs disabled.

The VPK @ONElua posted is correctly flipping X/O.

**Comment by ONElua** [comment]
ok...
thks for testing!!!!
