### ISSUE TITLE
Incompatibility with loading from ur0:/tai/config.txt for Henkaku Config

### ISSUE THREAD

**Issue by d4mation** [ONElua/AdrenalineBubbleManager#41]
It seems that on first start, this application creates `ux0:/app/PSPEMUCFW/sce_module/adrbblbooter.suprx`, but if `ux0:/tai/config.txt` does not exist, it skips over that entirely with no error. I load my Henkaku Config from `ur0:/tai/config.txt` instead, so this meant the plugin was not loaded.

However, I manually added `ux0:/app/PSPEMUCFW/sce_module/adrbblbooter.suprx` above `ux0:/app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx` similarly to the docs for adrbblbooter (https://sites.google.com/site/theleecherman/adrbubblebooter) and it gives me a `c2-12828-1` error and crashes my PSTV whenever I try to open a Bubble created by AdrenalineBubbleManager. I have to physically unplug the power cable to recover from it.

Any ideas? The only other Issue that references this is #25 and that was seemingly solved by just updating AdrenalineBubbleManager.

If it makes any difference, I'm running 3.65 Enso.

**Comment by ONElua** [comment]
Do you have the plugin for USBMC ?

**Comment by d4mation** [comment]
I'm using a SD2Vita in my case with https://github.com/xyzz/gamecard-microsd, actually. 

I just double-checked to confirm and running Adrenaline directly to load a game does work.

**Comment by ONElua** [comment]
please share your config.txt

**Comment by d4mation** [comment]
I've since removed adrbblbooter from my `ur0:/tai/config.txt` as it wasn't working for Adrenaline Bubble Manager for me.

```
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/gamesd.skprx.
ur0:tai/nonpdrm.skprx
ur0:tai/repatch.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/pngshot.suprx
```

**Comment by ONElua** [comment]
ux0:/app/PSPEMUCFW/sce_module/adrbblbooter.suprx
It is never mentioned that you should add to any config.txt
Reload config.txt and reboot your vita...
If you still follow the error, try to make a clean installation

**Comment by d4mation** [comment]
It is mentioned in the docs for adrbblbooter though. Granted, it seems to be a bit outdated. I made my best guess at changes based on what Adrenaline Bubble Manager was doing when copying its file out. Are you saying that no modifications to config.txt are necessary? 

I can try a fresh install of Adrenaline v6.3, but I actually did just that before installing ABM v5.01 so that _shouldn't_ change anything.

From adrbblbooter docs:
> 1)
> 
> To enable adrenaline bubble booter, copy 'adrbblbooter' folder to your PSVita storage root :
> 
> ux0:/adrbblbooter
> 
> 2)
> 
> Add 'adrbblbooter.suprx' first in line before 'adrenaline.suprx' under *TITLEID in HENKaku config.txt :

**Comment by ONElua** [comment]
""From adrbblbooter docs:"" is outdated

This is updated...
https://sites.google.com/site/theleecherman/adrbubblebooter/vpkedition

Please only reinstall adrenaline v6.3 an ABM5.01
https://github.com/ONElua/AdrenalineBubbleManager#instructions

**Comment by d4mation** [comment]
I did a full re-install of both Adrenaline and ABM and no luck. Left everything at defaults and everything in case it was some strange configuration issue.

**Comment by BaltazaR4** [comment]
Well d4mation, if the error comes after the black screen hangs a while, then is not an ABM issue, that error could be caused by a few things, maybe default driver and booter incompatibility with your game (1), if you downloaded those games from your psn account then you have to enable the npdrm plugin (1), if you previously launched adrenaline but for some reason it crashed and errored out, if your bubbles were made with a really old ABM version.

(1) try changing the driver in the edit bubble section by pressing circle, select the desired ABM bubble and press triangle, then you can edit the default config for the chosen bubble, the config list is as follows:
1. driver
2. booter
3. in game plugins
4. npdrm plugin

Try alternating the options in the edit bubble section for each bubble and see if that gets the problem solved

**Comment by richard1222** [comment]
got the same issue but my plugins are only for 3.65 and i didn't add anything extra to my config.txt file and the game crashes granted i only tested manhunt 2 uncensored but i'll test the others as well but i'm they will crash to can i get some help? thanks

**Comment by BaltazaR4** [comment]
richard1222 please open a new issue with specific error and telling you are using usbmc and 3.65 enso

**Comment by BaltazaR4** [comment]
d4mation, have you tried with various games or only with spyro?

**Comment by richard1222** [comment]
Ok

**Comment by richard1222** [comment]
d4mantion quick question? do you have the repatch plugin installed this could be the issue try to remove it then reload the tai config tbh i just removed it i think this was the cause of the crashing

**Comment by d4mation** [comment]
@BaltazaR4 I have tried with a few different games, including Spyro 1, Crash Bandicoot 1, and Persona 1 (For PSP).

@richard1222 I gave disabling rePatch and I get the same error unfortunately.
