### ISSUE TITLE
ABM Crashs while using usbmc plugin

### ISSUE THREAD

**Issue by richard1222** [ONElua/AdrenalineBubbleManager#42]
Version of firmware: 3.65 enso
System- PS Vita TV
using usbmc plugin

i'm having a issue with ABM it crashes right after i launch the bubble
 i have no extra lines in my config.txt, i did a fresh install of Adrenaline v6.3  and ABM to see if that helps nothing when it crashes and i need to unplug the system and wait for a reboot tbh i hope this does not damage the system and yes before you ask all the games crash for me any help would be appreciated thanks
All my plugins are 3.65 i checked btw

PS.  d4mation has the same issue as me   but has sd2vita instead of usbmc

**Comment by richard1222** [comment]
my bad i forgot to add just the bubbles crash and the error is same as d4mation

**Comment by BaltazaR4** [comment]
yes, but you get it right after the pic1 shows up or in your case it hangs a while in the black screen after the boot logo?

**Comment by richard1222** [comment]
it just locks up after it crashes and i gotta reboot the system

**Comment by BaltazaR4** [comment]
I got that part, but when do the bubbles crash exactly? when the pic1 is showing or after that you get a black screen for a while and then it crashes?

**Comment by richard1222** [comment]
um idk what i did but now it launches fine

**Comment by BaltazaR4** [comment]
ok

**Comment by richard1222** [comment]
thanks for the help

**Comment by BaltazaR4** [comment]
sure, I will close the issue now

**Comment by richard1222** [comment]
ok
