### ISSUE TITLE
[Request] Select custom image folder for batch image injections

### ISSUE THREAD

**Issue by T33Hud** [ONElua/AdrenalineBubbleManager#44]
It would be nice to have the ability to set a custom folder to pull images from when building the bubbles or batch injection after the bubbles are created. For example, if you wanted all of your PS1 bubbles to share the same background and splash, you could select ux0:ABM/PS1set/ and it would pull bg0.png and pic0.png from that folder for all the new bubbles in that batch. I have attached the set I am using for my PS1 and PSP bubbles as an example. Thanks

![bg0](https://user-images.githubusercontent.com/16843430/39724755-7dd5b30a-51fe-11e8-8d75-2d0f48e1c916.png)

![bg0_psp](https://user-images.githubusercontent.com/16843430/39724752-7da1f66e-51fe-11e8-9d42-a68f6ffcd900.png)

![pic0](https://user-images.githubusercontent.com/16843430/39724754-7dbb67ca-51fe-11e8-9b78-d7a913717c5d.png)

**Comment by ONElua** [comment]
OK
