### ISSUE TITLE
Getting error C2-12828-1 when launching any ABM created bubbles

### ISSUE THREAD

**Issue by ServerJock** [ONElua/AdrenalineBubbleManager#45]
Hello,

I tried different ISO but I always get this error message when launching them from the live area. I have Adrenaline 6.61 and I'm running ABM 5.01. I'm also running ux0 via SD2VITA. I've attached my config.txt files for ur0:tai and ux0:tai. I've seen 2 other tickets with similar issues and I tried their fix but it did not resolve my issue.
![2018-05-07-175535](https://user-images.githubusercontent.com/39069360/39727628-82b4afca-5221-11e8-914f-0c28dcd18a81.jpg)
![2018-05-07-175551](https://user-images.githubusercontent.com/39069360/39727633-86c6d016-5221-11e8-8d79-40d94c54bd2e.jpg)

Please help.

Thanks in advance.

**Comment by ONElua** [comment]
delete ux0:tai folder
reboot your vita, open first adrenaline 
and try adrenaline Bubbles

**Comment by ServerJock** [comment]
Thanks for your reply. I did the steps you provided but it did not work out at first. I still got the same error. An update then popped up for ABM 5.02, after I installed that it worked. It might be the original install that was problematic and the update fixed it. 

Thanks again, you can close this.

Cheers.
