### ISSUE TITLE
png lossy quality

### ISSUE THREAD

**Issue by Anonanon** [ONElua/AdrenalineBubbleManager#47]
![abm-issue](https://user-images.githubusercontent.com/1048428/40597111-5587f1fa-620d-11e8-801f-299c5673ca09.gif)

I'm trying to inject Sony's original bg0.png from genuine PSone Classics which is exactly 250 colors. But after the injection I noticed worse color banding. I ran a hash comparison and it comes up mismatched. I checked it in Photoshop and it seems the injected png has 136 colors. ABM is converting these pngs for no reason even when the png is already indexed 256 colors. I think the process needs to check that if the input png is already using 256 colors or less, it just needs to be copy and pasted as-is without needing to convert. If you do implement this, please do the same for all images including icon0, startup, etc.

**Comment by ONElua** [comment]
ABM converts the imgs to 8bits

**Comment by Anonanon** [comment]
Yes but I'm saying the image is already 8bit PNG with only 250 colors, why is ABM still converting these? It should just get copy and pasted to the correct directory.

**Comment by ONElua** [comment]
Send me the picture.. please
We have not yet improvised if an image is 8bit and the detection of the color palette.
But it's a good idea to do it

**Comment by Anonanon** [comment]
Yes, detection system is what I'm suggesting. That would be great.
Attached the Sony originals:
![bg0 psone classic](https://user-images.githubusercontent.com/1048428/40689046-75043694-636e-11e8-8d32-e94035164a24.png)
![bg0 psp](https://user-images.githubusercontent.com/1048428/40689048-76ac9a72-636e-11e8-9a84-985654ba3fb1.png)

**Comment by ONElua** [comment]
ok...
For now what can I do
it's just to put an 8bits convert option: Yes / No

**Comment by Anonanon** [comment]
Great, a manual option is good too! Just make sure YES is default so newbies don't get confused what 8bit means.

**Comment by ONElua** [comment]
https://www.dropbox.com/s/ozmh3r6sqmldlhr/AdrenalineBubbleManager_test8bits.vpk?dl=0
this its only for ux0:aABM/Setxx

**Comment by Anonanon** [comment]
Thanks I'll give it a try soon.
