### ISSUE TITLE
[Feature request] Import additional frame images

### ISSUE THREAD

**Issue by althonos** [ONElua/AdrenalineBubbleManager#48]
Hi there,

first of all, a huge thank for this tool, it is extremely comprehensive and really easy to use. I've been using it to give a more *official* look to some PSP games installed through Adrenaline, using a more refined `template.xml`. Unfortunately, since additional resources are not copied from the `ABM` folders, it is not possible at the moment to use additional frame images.

It would be great if `frameX.png` (with X from 1 to 7) could be added to the created bubble as well ! Or possibly all images from the selected folder, instead of simply the currently accepted 4 files.

Thanks again !

**Comment by ONElua** [comment]
ok
Please sendme a complete set.

**Comment by symbuzzer** [comment]
any news about this?

**Comment by althonos** [comment]
I don't really know any Lua, but I've been checking an XML parser that could be used to extract the names of the files directly within the `template.xml` file. I'll open a PR when I get that to work, but I'm a bit busy currently.

**Comment by ONElua** [comment]
Im working...
Only support 5 frames
frame1.png to  frame5.png
