### ISSUE TITLE
Not working with Adrenaline 6.4

### ISSUE THREAD

**Issue by ANU815** [ONElua/AdrenalineBubbleManager#49]
When I initially install Adrenaline 6.4, all of my bubbles work fine.  Until I reboot.  Once I reboot I get the "Could not load adrenaline_kernel.sprx" error.  Opening AdrenalineBubbleManager reinstalls the plugin, reboots.  Then all of my bubbles work again, but are back to Adrenaline 6.3.  I think BubbleManager needs to be updated to support 6.4?

**Comment by ONElua** [comment]
Working on it

**Comment by ANU815** [comment]
I'm sure you know it's again broken with Adrenaline 6.6.  Any way to future proof new version releases of adrenaline, or will your app always need to be updated?
