### ISSUE TITLE
Adrenaline-6

### ISSUE THREAD

**Issue by coderobe** [ONElua/AdrenalineBubbleManager#5]
This app is incompatible with the new Adrenaline-6

**Comment by mrgreezy3** [comment]
If you keep the adrenaline folder on your memory card the bubbles will work.  But you must first press the adrenaline bubble at least one time on boot up then bubbles will work.  Hope this helps for now

**Comment by coderobe** [comment]
That's merely a workaround, not a solution. New users won't get that folder either.

**Comment by BaltazaR4** [comment]
Onelua Team is working on a new version with added compatibility for Adrenaline v6 and new adrbubblebooter, still testing :)

**Comment by ONElua** [comment]
There is only an issue...I can not convert the images from the isos/csos/hbs within the ps vita to make them compatible for bubble installation
