### ISSUE TITLE
Constanly installing plugin and wanting to restart whenever opening the app

### ISSUE THREAD

**Issue by nicoformaggio** [ONElua/AdrenalineBubbleManager#50]
I Uninstalled the app and redownloaded the new version and now everytime I open the app it says the plugin is installed and that it wants to restart my vita. I assume there was something else I was meant to delete before reinstalling

**Comment by Lordjontan** [comment]
I have the same problem

**Comment by ONElua** [comment]
Omg !!!!! 
Im Fixed.
