### ISSUE TITLE
Error C2-12828-1 on launching any ABM-made bubble

### ISSUE THREAD

**Issue by MarioJaraR** [ONElua/AdrenalineBubbleManager#51]
Launching Adrenaline directly from it's bubble works without problems, but the ABM bubbles error out and crash my PSTV if I click OK on the error message. Using h-encore on PSTV 3.68. If it's relevant, I'm testing making bubbles for Valkyria Chronicles II, SFA3 MAX and Final Fantasy III.

**Comment by ONElua** [comment]
refer to issue https://github.com/ONElua/AdrenalineBubbleManager/issues/43
 maybe something is wrong in your config.txt

**Comment by ONElua** [comment]
please show me capture your config.txt (in ux0:tai and ur0:tai)

**Comment by MarioJaraR** [comment]
![2018-07-02-145851](https://user-images.githubusercontent.com/22383407/42181452-dca5f7f6-7e08-11e8-8523-21d013d7bf89.jpg)
![2018-07-02-145857](https://user-images.githubusercontent.com/22383407/42181453-dccdde42-7e08-11e8-8a33-5d36905a793e.jpg)
Here's my ur0:tai/config.txt. I don't have a ux0:tai/config.txt...

**Comment by RadicalR** [comment]
I am also having the same problem. I'll attach my logs in a second.

**Comment by ONElua** [comment]
Try fisrt update db.
or uninstall and reinstall Adrenaline v6.4 -> ABM 5.06

**Comment by ONElua** [comment]
send me DM in twitter @gdljjrod
please!!!!
