### ISSUE TITLE
Error C2-12828-1 on all bubbles post-update

### ISSUE THREAD

**Issue by Tomcoid** [ONElua/AdrenalineBubbleManager#52]
Updated ABM to 5.06, as well as Adrenaline to 6.4, Bubbles no longer work, however Adrenaline (and games started through adrenaline) work perfectly fine.

**Comment by ONElua** [comment]
Version and sd2vita ???

**Comment by Tomcoid** [comment]
3.65 ENSO, and yes am using sd2vita

**Comment by ONElua** [comment]
show me config.txt
and screenshot in ux0:app/PSPEMUXXX/data/
please

**Comment by ONElua** [comment]
Did you updated ABM first and then adrenaline last? or adrenaline first and ABM last?

**Comment by Tomcoid** [comment]
I updated ABM first, and then Adrenaline. I will post the screenshots when home

**Comment by ONElua** [comment]
Then is not an ABM related issue, just open ABM again and the bubbles should work

**Comment by Tomcoid** [comment]
Sorry I meant the other way around

**Comment by Tomcoid** [comment]
![36566517_1821937347919537_9113176176905420800_n](https://user-images.githubusercontent.com/40776438/42241354-404759ce-7ed8-11e8-9f68-c6d06b070e32.jpg)

This is my Config, and i do not have a folder named PSPEMUXXX

**Comment by ONElua** [comment]
send me DM in twitter @gdljjrod
please!!!!
