### ISSUE TITLE
Error C2-12828-1 when opening the bubbles I created with the tool

### ISSUE THREAD

**Issue by lechatvert** [ONElua/AdrenalineBubbleManager#53]
Same issue as a lot of people... This is my config.txt in ur0:tai: 
![99c66fcd-0d7c-4778-b215-dd5efbc5d6cd](https://user-images.githubusercontent.com/25781554/42235532-112e3c32-7ec6-11e8-8f2c-f1689b59dcbd.png)
and this is the one in ux0:tai: 
![d85d761f-2389-49f4-b1f4-fbf41270aeea](https://user-images.githubusercontent.com/25781554/42235619-5311cf88-7ec6-11e8-8f54-b6c394068990.png)
Is there something wrong in them? If so, can you please tell me what’s wrong?

**Comment by ONElua** [comment]
Version and sd2vita??

**Comment by lechatvert** [comment]
3.65 Ensō H-Encore. Official 32 GB memory card, no SD2Vita

**Comment by ONElua** [comment]
please delete ux0:tai/config.txt

show me in ux0:app/PSPEMUXXXX/data

**Comment by lechatvert** [comment]
There you go... 
![2caf7a7b-c99c-4447-8b59-33ca1b0f0c7a](https://user-images.githubusercontent.com/25781554/42243182-71722be0-7ede-11e8-9457-cdc581ffac8c.png)
![5dc673c9-ff3c-482c-bda6-f46c47cc4df1](https://user-images.githubusercontent.com/25781554/42243183-71859fea-7ede-11e8-9dd6-9d1bcee52270.png)

**Comment by lechatvert** [comment]
There you go...
![8ed223aa-1b61-41a0-ab1e-d91a6e73c816](https://user-images.githubusercontent.com/25781554/42243212-938f3038-7ede-11e8-8e07-6a8aa0a54d13.png)
![fe6ab753-22be-40a2-b78c-a38989d63272](https://user-images.githubusercontent.com/25781554/42243213-939ddc3c-7ede-11e8-9a23-51ed87f5a46d.png)

**Comment by ONElua** [comment]
send me DM in twitter @gdljjrod
please!!!!

**Comment by lechatvert** [comment]
Well, I can’t. When I enter your account name, I can see your profile, but it doesn’t let me send you a DM. I can DM other people but not you... I even tried to follow you, but it still doesn’t work...

**Comment by lechatvert** [comment]
Can you try to send me one? My twitter is @LeChatVert_

**Comment by lechatvert** [comment]
It worked, thanks!
