### ISSUE TITLE
How to fix "startup.png" images

### ISSUE THREAD

**Issue by haganenox** [ONElua/AdrenalineBubbleManager#55]
Hello everyone, thank you very much for all the efforts you make with this wonderful application.

My question is the following one, I create all the images with the dimensions that you indicate, nevertheless, the image startup.png, appears cut when creating the bubble, how could fix that? thank you again.

![img_0018](https://user-images.githubusercontent.com/26688450/42357210-c50247dc-80a4-11e8-9c77-5d629e221731.jpg)

![img_0017](https://user-images.githubusercontent.com/26688450/42357212-c8dcfa64-80a4-11e8-82de-d96dc4a13c8f.jpg)

![img_0016](https://user-images.githubusercontent.com/26688450/42357215-cc219d7e-80a4-11e8-9653-7899392b43c5.jpg)

**Comment by haganenox** [comment]
Ok...
[Corpse Party.zip](https://github.com/ONElua/AdrenalineBubbleManager/files/2173190/Corpse.Party.zip)

Thanks a lot!

**Comment by haganenox** [comment]
Omg!!!! Thanks

**Comment by haganenox** [comment]
I installed the file that you left in the post, then I checked all the dimensions of the images, I made the bubble again and it keeps appearing the same ... :(

**Comment by haganenox** [comment]
Works! It works! ... thank you very much for answering my question ... the first thing I did was to check the dimension of all the images, then I deleted the version I had of ABM and reinstalled it.

**Comment by haganenox** [comment]
Last question ... how do you place the icon on the side? mine appears at the center ...

**Comment by ONElua** [comment]
template.xml (pspemu or ps1emu)
https://www.dropbox.com/sh/3mh70bxihx5tgx1/AADSqyIu1-9Cegkxz_ywmP4oa?dl=0
Wait to monday to release version
