### ISSUE TITLE
Creating more than 14 bubbles is impossible

### ISSUE THREAD

**Issue by Hellghast** [ONElua/AdrenalineBubbleManager#57]
The latest version of the application can not create more than 14 bubbles. When creating 15, a system error is written. Prior to this, there was version 5.03, this was not observed.
UPD
5.03 is installed on the fat version, and the problem with the slim version. 5.03 Slim version also does not create more than 14 bubbles

**Comment by Hellghast** [comment]
Screenshot https://mega.nz/#!MjxCGQzZ!z9ETFtWcCb9kD4HoDwjkcoNOr_InJC2YXmROfvhYYqM

**Comment by ONElua** [comment]
All your games have icon0.png ???

**Comment by Hellghast** [comment]
Yes
I have two consoles, Fat 128Gb and Slim 256Gb. Adrenaline 6.3, on the Fat version - 17 bubbles, but only 15 bubbles can be created on the Slim version, I tried different games, created the same bubbles on both consoles, but pspemu015 is not created on the Slim version. A folder appears on the path ux0:app/new with bubble resources

**Comment by ONElua** [comment]
ok
delete all PSPEMUXXX bubbles and update.db
Try again please.

**Comment by Hellghast** [comment]
On sd2vita It did not help. On the original memory do this do not see the point. Or will it help in solving the problem?

**Comment by Hellghast** [comment]
Thanks for your advice and responsiveness) The problem is solved) On the memory card there was only 50MB and this program was not enough to create the next bubble) Sorry for the trouble)

**Comment by ONElua** [comment]
😡
