### ISSUE TITLE
Option change livearea style

### ISSUE THREAD

**Issue by Kenanmu** [ONElua/AdrenalineBubbleManager#58]
First of all I want to thank you for this cool app. I would like to know if in the future you have planned to put the option to customize the livearea style. For example change the pspemu style for a5 style or others. Thanks again and sorry for my bad english.

**Comment by ONElua** [comment]
you can use option SET1 to SET3 or Injected imgs in put your own template.xml
PD: sorry badengrish.

**Comment by ONElua** [comment]
In Wip
a5, pspemu, ps1emu and psmobile

**Comment by ONElua** [comment]
https://github.com/ONElua/AdrenalineBubbleManager/commit/f0a99a5a82aea70b1d94c87b1c8bcc936246e147
