### ISSUE TITLE
Non stretched icons

### ISSUE THREAD

**Issue by tatundria** [ONElua/AdrenalineBubbleManager#6]
Is is possible to add real psp icons (non stretched) to the bubbles instead of the vita stretched ones?

**Comment by BaltazaR4** [comment]
The icons used on livearea? well, will talk about that to gdljjrod

**Comment by tatundria** [comment]
Any solution on this? I mean, the bubbles still have stretched icons on ABM 3.07. What are 8bits icons?

**Comment by BaltazaR4** [comment]
will probably do a fork fir a modded version with the option to create the livearea icon with original psp size or full bubble size, 8bit icons is the kind of icon that works for vpk to install, otherwise when trying to install a vpk with icons with a wrong size/format the installation will return error

**Comment by tatundria** [comment]
Thank you! I´ll wait for that modded version then

**Comment by BaltazaR4** [comment]
Well,I tried a few times on the non stretched icons deal, but no success, the icon0 to be installed has to be 128*128 and original psp icon0 is 144*80

**Comment by BaltazaR4** [comment]
Well,I tried a few times on the non stretched icons deal, but no success, the icon0 to be installed has to be 128x128 and original psp icon0 is 144x80

**Comment by tatundria** [comment]
Oh what a pity. Actually, earlier versions of ABM had original psp icons. With ABM 3.0 original psp icons were restored after rebuilding database

**Comment by BaltazaR4** [comment]
Yes, because v3.01 and earlier used a psp cloned game for each bubble, that's why the psp icons will show on the bubble, on v3.05 and later a ps vita cloned app/game is created for each bubble that's why the icons for v3.05 and later must be 128x128, otherwise an installation error will occur

**Comment by DavisDev** [comment]
I have already found a solution, in the next update, hopefully it will be added. 
@BaltazaR4 I hope it's what everyone is looking for xD

**Comment by tatundria** [comment]
Great! Thanks a lot!!
