### ISSUE TITLE
xmc0: partition not read

### ISSUE THREAD

**Issue by JAKAMY** [ONElua/AdrenalineBubbleManager#62]
Hi, I am using storagemanager to automount the xmc0 partition on boot and Adrenaline Bubble Manager doesn't find Adrenaline's folder on it.
I unmounted and remounted on vitashell just in case and it still is not finding anything.
I use enso 3.65

**Comment by ONElua** [comment]
Do you have Adrenaline in xmc0? or your iso/cso in xmc0 ??

**Comment by JAKAMY** [comment]
Yes all data and iso are in xmc0:

**Comment by JAKAMY** [comment]
Yes

**Comment by ONElua** [comment]
If you mount imc0 as ux0 you must install adrenaline there too

**Comment by JAKAMY** [comment]
I don’t have an imc0 partition as I use a vita 3G 1000
My system boot into the gcm (sd2vita) and mounts it as ux0
Adrénaline latest is installed there
Storagemanager plugin at boot mounts the Sony vita memory card as xmc0 (McD)
Under adrenaline in the option I use xmc0 as data path and memory card as USB 
Adrenaline shows then all my psp content from xmc0.
When I start adrenaline bubble manager 
It doesn’t find anything. 
Would there be anyway to manually specify xmc0 for a scan under adrenaline bubble manager? It would help know if it can access the partition or not at least

**Comment by ONElua** [comment]
ok...
i see my error.
wait next release

**Comment by ONElua** [comment]
please try mount as imc0:

**Comment by JAKAMY** [comment]
i had the MCD mount as imc0 at boot and it works on adrenaline bubble manager.
so it seems like it can't read xmc0

**Comment by ONElua** [comment]
ok..thks
I have the fix.

**Comment by ONElua** [comment]
v5.09 work?

**Comment by JAKAMY** [comment]
Yes it works flawlessly and straightforward with xmc0, thanks a lot.
