### ISSUE TITLE
System hangs up when loading "original games" on Castlevania: Dracula X chronicles

### ISSUE THREAD

**Issue by asdfqwer426** [ONElua/AdrenalineBubbleManager#63]
Moved my Castlevania: DXC saves from old PSP to Vita with latest adrenaline/bubblemanager setup on a fresh enso 3.65 install. 1K with PSVSD set as ux0:

when I boot the game directly from adrenaline, the "original games", ( symphony of the night and rondo of blood) load and work perfectly.

when I created the bubble, the PSP game will boot up and play fine, but when either of the "original games" are loaded the game will crash and move back to the XMB, but the card won't be read. when I go back to the vita home screen, programs will simply hang on a black screen instead of load. when I power down, it get a spinning circle. After holding down the power button to shut down it brings me to the recovery menu where I just restart and then everything works fine again.

**Comment by ONElua** [comment]
try another mode
BOOT.BIN

**Comment by asdfqwer426** [comment]
Changing the driver from default inferno to march33 seems to have fixed it! Sorry I somehow missed that whole extra settings menu there. Definitely user issue, not program issue. 

BOOT.BIN setting made the whole game crash like mentioned above, so I set it back to EBOOT.BIN. 

Thank you for the quick help and for this awesome program.

**Comment by ttyborg** [comment]
That's the case for Splinter Cell: Essentials as well, for both EUR and USA versions.
