### ISSUE TITLE
reboot loop is here fuuuuuuuuck

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [ONElua/AdrenalineBubbleManager#64]
i'm updated my bubble manager today and after install its say adrbubblebooter plugin has been installed
we need to restart your PS Vita
after i'm press X the vita reboots.
i'm starting h-encore and after start bubble manager and its say same
fuuuuuuccckkkkkkkk

**Comment by ONElua** [comment]
you have sd2vita???

**Comment by falthgorn** [comment]
I'm sorry to interfere, but exactly the same thing happens to me.
I do have sd2vita and the plugins I have in ur0.

**Comment by ONElua** [comment]
Reboot your Vita
First run h-encore
install adrenaline, Make sure Adrenaline works correctly,
install ABM v5.09

**Comment by ONElua** [comment]
Try in ABM v5.10

**Comment by falthgorn** [comment]
Perfect with ABM v5.10

**Comment by ONElua** [comment]
Thanks for reporting the bug !!!

**Comment by TheOneEyedGrimReaper** [comment]
yeah yeah i have sd2vita too.
tanks working fine with the 5.10
