### ISSUE TITLE
Project DIVA Extend Translation plugin not loading via Bubble

### ISSUE THREAD

**Issue by diegorocha2007** [ONElua/AdrenalineBubbleManager#66]
Well, I'm trying to use the translation patch for this game, which is a .prx plugin, and the patch is recognized when lauching via Adrenaline, but when lauching via bubble on the LiveArea it's not.

Can you look this up, please?

The patch can be found here:
http://projectdiva.wiki/Translation+Patch+%28extend%29

Thanks in advance!

**Comment by ONElua** [comment]
1) Try with another driver NP9660 in ABM 
or
2) Change driver in Adrenaline menu -> Booter tab to NP9660
then close the menu and re-start the bubble.

**Comment by diegorocha2007** [comment]
Thank you, changing to NP9660 on ABM solved the problem. Now the plug-in is loading as expected.
