### ISSUE TITLE
Injecting images error

### ISSUE THREAD

**Issue by Lvieira21** [ONElua/AdrenalineBubbleManager#68]
Creating bubbles are working perfect with me, but whenever I try injecting images, I get "System message: Sorry, there was an installation error".

PS Vita PCH-1001 - 3.68 Enso - ABM 5.11

**Comment by ONElua** [comment]
sendme a setpack.

**Comment by Lvieira21** [comment]
Hey!
I was trying again today, and after changing the Set and enabling 8-bit conversion (Dunno if that contributed), it started to work.

Sorry for the issue ticket, I coundt find any help on reddit, since this version is a new one, I thought it was an update problem.
