### ISSUE TITLE
it makes adrenaline crash and the new game bubble.

### ISSUE THREAD

**Issue by djmega818** [ONElua/AdrenalineBubbleManager#7]
I use henkaku from the wed, no enso. i just made one bubble from a iso psp game but after doing that happens, it makes crash the bubbles

**Comment by BaltazaR4** [comment]
This version was tested with enso, will test it with henkaku R10 to see what happens, hopefully will get it sorted

**Comment by BaltazaR4** [comment]
by the way, have you tried with diferent driver setup?

**Comment by ONElua** [comment]
What's the game?
iso clean?? patched??

**Comment by djmega818** [comment]
Iso clean i guess. It was castlevnia x. And regular henkaku 10. After doing the bubble it doesn't open. The bubble and adrenaline thanks

**Comment by ONElua** [comment]
Adrenaline v6fix  is installed?

**Comment by ONElua** [comment]
Well..
Im try Castlevania Dracula X Chronicles EUR 
and working fine!!! 
With driver Inferno & Eboot.bin
