### ISSUE TITLE
Unable buttons while loggin in Adrenaline or playing PSP/PSX games after using this app

### ISSUE THREAD

**Issue by SysmaEngineer** [ONElua/AdrenalineBubbleManager#70]
There's a problem when I execute Adrenaline Bubble Manager for the first time after testing Adrenaline: it makes impossible move or respond to buttons. I knew this situation only happens when executing ABM v. 5.12 (it requires a neccesary reboot after executing for the first time).

I have a Ps Vita in 3.60, with Enso, Adrenaline v. 6.61-6.7, generated config.txt file by Autoplugin 3.17... I don't know what details to say could be useful...

**Comment by ONElua** [comment]
Show me your config.txt (ux0:tai and ur0:tai)

**Comment by SysmaEngineer** [comment]
It's attached. It was created by Autoplugin 3.17 for ur0 (I use SD2Vita)

[config(autoplugin).txt](https://github.com/ONElua/AdrenalineBubbleManager/files/2314815/config.autoplugin.txt)

**Comment by ONElua** [comment]
Do you have an official memory?
Do you really use so many plugins?

**Comment by SysmaEngineer** [comment]
Yes, I've an official memory but I don't really use it.
could the number of used plugins be the fact? I don't use three of them. I'll prove this is the cause.

**Comment by ONElua** [comment]
Try update the app.db (menu recovery)
and install only plugins: sd2vita, nonpdrm, repatch (autoplugin)
in a clean config.txt

**Comment by SysmaEngineer** [comment]
It seems it works as you say: I re-built the database and used a clean config.txt from mlthaku.tk. After installing Adrenaline and launching AMB for the first time, Adrenaline responds to the buttons! I'll try again updating the app.db after launching AMB and Adrenaline and the bug persists.

The resolution must be installing a few of plugins, then. Thank you for your help!

**Comment by SysmaEngineer** [comment]
It seems it works as you say: I re-built the database and used a clean config.txt from mlthaku.tk. After installing Adrenaline and launching AMB for the first time, Adrenaline responds to the buttons! I'll try again updating the app.db after launching AMB and Adrenaline and the bug persists.

The resolution must be installing a few of plugins, then. Thank you for your help!
