### ISSUE TITLE
ABM no input

### ISSUE THREAD

**Issue by muttlly** [ONElua/AdrenalineBubbleManager#72]
Hi, I have just installed ABB and ABM and created my first bubble. It launches fine and goes into the game, but none of the buttons or controls work. To get them to work I have to enter the adrenaline menu and press the D pad, then return to the game, and everything works OK. I uninstalled ABB and ABM and rebooted, but the same thing happens when I enter Adrenaline now, no controls to get to my games until I open the Adrenaline settings menu. Any ideas please?

**Comment by ONElua** [comment]
Try
https://github.com/ONElua/AdrenalineBubbleManager/issues/70

**Comment by muttlly** [comment]
Thank you, I tried rebuilding the database app.db, but that's made no difference. I'm a bit nervous about doing a fresh config.txt as I'm worried about things not working anymore. Just to point out, this is happening every time I run a PSP game from a bubble, or start Adrenaline on its own. I always have to enter the settings menu and move the D pad before any controls work. It doesn't matter if I reboot, it's the same. This only happened after installing ABM and ABB. Here is my config:

# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/gamesd.skprx
ur0:tai/repatch.skprx
ur0:tai/storagemgr.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/lolicon.skprx
ur0:tai/kuio.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/download_enabler.suprx
ur0:tai/shellbat.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*ALL
ur0:tai/vsh.suprx
ur0:tai/vitagrafix.suprx
ur0:tai/oclockvita.suprx

**Comment by ONElua** [comment]
only 1 plugin for sd2vita
ur0:tai/storagemgr.skprx or ur0:tai/gamesd.skprx
and only 1 config.txt in ur0:tai (no ux0:tai folder).

**Comment by muttlly** [comment]
Thanks for pointing that out☺️

**Comment by ONElua** [comment]
reset config.txt and use autoplugin for install only sd2vita first.
unnistall ABM
unistall Adrenaline
and reinstall both

**Comment by muttlly** [comment]
OK, so I tried that and it worked with adrenaline, but when I reinstalled ABM and made some bubbles, the same thing happened again. Its a minor problem really, I can still access my games, it's just a nuisance, but I can live with it. Thanks again.

**Comment by ONElua** [comment]
They must be the extra plugins that you do not need: vsh, kuio

**Comment by muttlly** [comment]
OK, I've removed both of those now, but still have the same problem I'm afraid...

**Comment by ONElua** [comment]
You need to restore the config.txt
and just install the necessary plugins: sd2vita, nonpdrm, repatch.
and only 1 config.txt in ur0:tai (no ux0:tai folder).
