### ISSUE TITLE
Batch process, modify text/bubble options before processing

### ISSUE THREAD

**Issue by t0mtaylor** [ONElua/AdrenalineBubbleManager#73]
Hi

It would be much better to make modifications to Bubble Title before then batch processing, otherwise you have to sit and confirm every Bubble Title, where this could be automatic :)

This means you could modify any number or titles, start the batch processing, go make a cup of tea - without pressing R2 for each title to process!

**Comment by ONElua** [comment]
https://github.com/ONElua/AdrenalineBubbleManager/releases

**Comment by t0mtaylor** [comment]
Nice work will try this out, thanks @ONElua 👍
