### ISSUE TITLE
Bubble Compression - compress images, xml, etc

### ISSUE THREAD

**Issue by t0mtaylor** [ONElua/AdrenalineBubbleManager#74]
Hi

It appears the Bubbles can add alot of bloat and use up much storage on ux0 (im using a 2tb hdd)

Could we add image compression (using optipng, jpegtran) and xml compression (new lines, spaces, etc)

https://gist.github.com/jney/214659/720377e9c3d88dab2a06c1ef4cc1418d4cc025da
https://github.com/google/snappy

LZ4 could provide really fast compression overall also once assets such as images and xml are optimised - https://github.com/witchu/lua-lz4 (https://lz4.github.io/lz4/)

This could be implemented in 2 stages:

1) Compress during new bubble creation
2) Check and compress existing bubbles as a batch process

Thanks

**Comment by DavisDev** [comment]
Hello Dear @t0mtaylor !
The resources that we create for the bubbles are as optimized as possible, besides the system **PS Vita** has certain **requirements**, so we can not simply compress or reduce sizes,
Even so, you can add extra modules by os.require for code like lz4, or simply add extra scripts.
If you can help, you will be welcome.
