### ISSUE TITLE
Adrenalin crash

### ISSUE THREAD

**Issue by gleb2k** [ONElua/AdrenalineBubbleManager#75]
Adrenaline Bubble Booter is crashing Adrenalin
Hi, I have PSTV (3.60). Just installed latest Adrenalin 6.7, than ABM 5.14 and also bubblebooter 0.8. PS1 games start with no problems, 

Now, whenever I open Adrenaline settings and scroll past the SAVE STATE, adrenaline crashes. I need to reboot the Vita in order to use it again.

**Comment by ONElua** [comment]
This is not an ABM problem.
You will have to reinstall Adrenaline completely
