### ISSUE TITLE
'Mark All' software titles to allow rebuild of bubbles without marking invididually 

### ISSUE THREAD

**Issue by t0mtaylor** [ONElua/AdrenalineBubbleManager#76]
Hi :)

Could we have a new feature, which will 'Mark All' software titles to allow rebuild of all bubbles without marking individual?

This will save a lot of time, and help with development of new features, etc

Thanks

**Comment by ONElua** [comment]
I'm not sure if I'm understanding you... Can you elaborate please?

**Comment by ONElua** [comment]
ok
