### ISSUE TITLE
'Cleanup' task to 'Auto-delete' bubbles when original software title does no longer exist on drive/partition

### ISSUE THREAD

**Issue by t0mtaylor** [ONElua/AdrenalineBubbleManager#77]
Hi :)

Could we have a new feature, where we could select a 'Cleanup' task to 'Auto-delete' bubbles when original software title does no longer exist on drive/partition

This would help managing software titles due to storage free space constraints, etc

Thanks

**Comment by ONElua** [comment]
So, you want to delete automatically bubbles when the game (iso/cso/pbp) is no longer on the memory?

**Comment by t0mtaylor** [comment]
Nice progress :) 👍
