### ISSUE TITLE
Cutscenes are black on FFT-0

### ISSUE THREAD

**Issue by sons-of-batman** [ONElua/AdrenalineBubbleManager#78]
When I open it through Adrenaline or use boot.bin/old eboot.bin, however, the cutscenes work fine. There is a reddit thread from April concerning this issue, but no solution was found.

**Comment by ONElua** [comment]
Try with DriverNP9660

**Comment by ONElua** [comment]
Final Fantasy Type-0 is workign with Driver Inferno.
Try another iso
