### ISSUE TITLE
Castlevania Dracula X Chronicles causes Error

### ISSUE THREAD

**Issue by ajhix36** [ONElua/AdrenalineBubbleManager#8]
Hello, with Castlevania, when you load Symphony of the Night, and I would assume other games that reload into a subgame, it spits you back out to the Adrenaline menu, with the message "The game could not be started (8002013a)."

**Comment by BaltazaR4** [comment]
Will see about that, it sounds like an issue with Lmans plugin

**Comment by ONElua** [comment]
Try...
driver : NP9660
bin: EBOOT.BIN
