### ISSUE TITLE
ABM crashes on startup

### ISSUE THREAD

**Issue by kaymynd** [ONElua/AdrenalineBubbleManager#80]
Unsure why but ABM crashes when loading. This only began to happen after adding psp games. I now have around 150 psp games. Adrenaline will only show 126 at a time and must be reboot to show other games, this may be related. I cannot use the app due to the crashing at startup. It scans a good amount of the games but always gets stuck on one near the end and freezes.

**Comment by ONElua** [comment]
Possibly you have a corrupt iso/cso/pbp game

**Comment by kaymynd** [comment]
I've tested and played all the iso/pbp games (don't have any cso) and none seem to be corrupted.
I've moved the games around and the app seems to freeze at usually the same place in the scanning list, but with a different game due to me moving them around. I'm going to try removing some games to be under the adrenaline 126 psp game limit and see if this fixes the problem. Will update with the results after work.
