### ISSUE TITLE
h-encore 2.0 + Adrenaline 6.8

### ISSUE THREAD

**Issue by craigerskine** [ONElua/AdrenalineBubbleManager#84]
The combination of these two new additions causes the following error message when I launch a game made by AdrenalineBubbleManager:

`Could not load adrenaline_kernel.skprx. Please reboot or use the AdrBubbleBooterInstaller`

I can launch Adrenaline and play games that way perfectly fine. It's just when I launch a bubble made by ABM.

**Comment by ONElua** [comment]
in WIP
