### ISSUE TITLE
PSP icons are stretched

### ISSUE THREAD

**Issue by tatundria** [ONElua/AdrenalineBubbleManager#86]
How can I create normal PSP icons? When I create them with ABM they looke stretched like the Ps Vita ones, not like the PSP ones

**Comment by tatundria** [comment]
Yes, but I mean... can I activate the non-stretched mode with L when I use images from online resources or custom images?

**Comment by ONElua** [comment]
ok
in WIP

**Comment by stuermera** [comment]
Same issue here. Bubbles are mad normal (not stretched). Bubble on Livearea has stretched picture and isn't working. 

Get an error code "AdrBubbleBooter Installer by LMAN. Press START to install."

I press START, reboot but same error.
Bubbles were working with Adrenaline 6.7 and BubbleManager 5.16.

**Comment by ONElua** [comment]
Press L to toggle between stretched and non stretched icons
If you are using the image injection opción the icons must be 128*128 otherwise the icon will look stretched

**Comment by tatundria** [comment]
It doesnt work. Even with 128x128 size icon looks stretched. Can't get the psp icon size

**Comment by ONElua** [comment]
try in v5.21
Added FullBubble-Non Streched in inject resources (press L)

**Comment by Badcatalex** [comment]
I'm having an issue akin to this in the latest version of ABM.


I'm trying to apply the Persona custom bubble assets by Drazini from the official repository to Persona 1 thru 3P, but whenever it is applied, the icons get squished horizontally like a PSP icon, and doesn't properly appear as a proper bubble icon (in the same style as the native Vita bubbles).
Manually applying the assets and pressing L to make it applyin the same style as the native Vita bubble 128x128 px icons does *not* make it apply in that manner.
