### ISSUE TITLE
Constant prompt to install Bubble Booter

### ISSUE THREAD

**Issue by Eds1989** [ONElua/AdrenalineBubbleManager#88]
I've had a read through the readme file, and I see a note about a "setting" that needs changing to prevent constant prompt of plugin install, but I don't think it's really clear what setting that is.

I have Adrenaline 6.8 installed, with the adrenaline kernel plugin added to my tai config file.
I have created a whole bunch of bubbles using ABM, but every one I launch, I am prompted to install the bubble booter plugin.
After reboot, Adrenaline no longer works, as the adrenaline kernel plugin looks to have been deleted.

Can anyone explain more clearly what setting I am supposed to change in order to prevent this?

**Comment by ONElua** [comment]
model, version, sd2vita???
ABM version???

**Comment by Eds1989** [comment]
Well I don't really understand why, but I just loaded up ABM for the first time since creating my bubbles, and I was prompted to install the booter plugin.

I did it when prompted, and now my bubbles are working.

I'll close this issue, as I'm not clear how it go into that state.
it's a 2000, 3.65 with h-encore 2.0 and enso. Using SD2Vita and latest build of adrenaline and ABM.

**Comment by stuermera** [comment]
I have the same issue. But installing the plugin doesn't work for me.
