### ISSUE TITLE
Issues with Adrenaline 6.8 and ABM 5.20

### ISSUE THREAD

**Issue by stuermera** [ONElua/AdrenalineBubbleManager#90]
Adrenaline 6.7 and ABM 5.12 was workibg perfect. Since the latest updates I get constant messages to install "AdrBubbleBooter Installer" and reboot... But that doesn't work.

Also created bubbles are horizontally stretched.

Already tried deleting and reinstalling both - Adrenaline and ABM. Without success.

Any idea? 
I am on Enso 3.65.

**Comment by ONElua** [comment]
model
version
please send me your config.txt (ux0&ur0)

**Comment by ONElua** [comment]
Add the Adrenaline line to your config.txt either manually or by using autoplugin
Make sure you only have the config.txt at ur0

**Comment by ONElua** [comment]
Press L to toggle between stretched and non stretched icons
If you are using the image injection opción the icons must be 128*128 otherwise the icon will look stretched

**Comment by svefn** [comment]
having the same issue as well (1k henkaku 3.60). what i did:

install Adrenaline v6.8 following screen instructions and made sure Adrenaline works correctly.
install ABM v5.20, reboot, open Adrenaline, then close and create bubbles.
bubbles done but opening a bubble will black screen with lman asking to press Start to install and reboot.
after rebooting, i noticed adrenaline_kernel.skprx is gone in ux0:app/PSPEMUCFW/sce_module/.

`# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from molecularShell for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
# henkaku.skprx is hard-coded to load and is not listed here
ur0:tai/vitastick.skprx
ur0:tai/vitabright.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/reF00D.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*main
ur0:tai/shellsecbat.suprx`

**Comment by ONElua** [comment]
try v5.21
Update anf fix all your bubles in this option
![2019-03-11-090018](https://user-images.githubusercontent.com/25811032/54135463-774fd780-43df-11e9-81d2-883f3440369a.png)
