### ISSUE TITLE
Vita adrenaline bubbles manager bad argument issue

### ISSUE THREAD

**Issue by Bencurtis0503** [ONElua/AdrenalineBubbleManager#92]
- Version of firmware: 3.60
- Version of ABM: 5.21
- Version of adrenaline:  6.61

I have had no issues creating bubbles or the application loading until this evening where the screen I’m used to getting is not loading instead I get a grey screen with writing and a error message saying

Bad argument #1 to ’byte’ (string expected, got nil)

This is below a few lines of text that don’t contain any info and one that I guess says the file with the problem
Ux0:/app/ADRBUBMAN/system/commons.lua

I have not changed anything in in any of the ux0 files apart from updating pkgi and installing.

**Comment by ONElua** [comment]
send screenshot from the error

**Comment by Bencurtis0503** [comment]
Hi



This is the screen that come up when I open bubble manager, 

Thanks

Ben

**Comment by ONElua** [comment]
uplod your screen here!!!
![image](https://user-images.githubusercontent.com/25811032/54461526-67fbc180-4732-11e9-85fe-284f41096921.png)

**Comment by dicelander** [comment]
I was having the same problem. I forgot to screenshot it, but found the culprit: a corrupted bubble.

It wouldn't run, so i deleted it through live area as normal and ABM was running again

**Comment by Bencurtis0503** [comment]
Thank you that was the problem much appreciated
