### ISSUE TITLE
Make compatible with new Adrenaline version (support GTA Native patch)

### ISSUE THREAD

**Issue by Sprucuis** [ONElua/AdrenalineBubbleManager#93]
No description given.

**Comment by Sprucuis** [comment]
Eehhh...

**Comment by Sprucuis** [comment]
La-li-lu-le-lo...

**Comment by ifonefox** [comment]
Spamming to bump your issue isn't going to help. Here's a workaround to make it compatible:

From https://github.com/ONElua/AdrenalineBubbleManager/issues/94#issuecomment-478302123

> You can disable the option check adrenaline so adrenaline stays in v6.8
>
>Adrenaline version check.
>This option disables/enables ABM to check the Adrenaline version you have installed in your ps vita.
this adrenaline in v6.8
>  ![image](https://user-images.githubusercontent.com/25811032/55283308-7c88ae00-531d-11e9-8bd6-8c0c69e23ed6.png)

**Comment by Sprucuis** [comment]
ifonefox, Okay and... Sorry for that ^_^
