### ISSUE TITLE
Please update ABM compatible with adrenaline 6.9

### ISSUE THREAD

**Issue by asakapa619** [ONElua/AdrenalineBubbleManager#94]
I cant update my adrenaline to 6.9, whenever i open ABM it shows some system error then it keeps my adrenaline reverting back to 6.8 after an auto-reboot..

**Comment by ifonefox** [comment]
This issue has already been reported at #93. ABM depends on Adrenaline Bubble Booter, which currently only supports up to 6.8. ONElua's fork of Autoplugin recently added support for the GTA patch (ONElua/Autoplugin@ec739e7e851bad12bd949da48ba84cee008d0d58), so the team is already aware of Adrenaline 6.9.

**Comment by ONElua** [comment]
Adrenaline version check.
This option disables/enables ABM to check the Adrenaline version you have installed in your ps vita.
this adrenaline in v6.8 
![ExtraSettings](https://user-images.githubusercontent.com/25811032/55283308-7c88ae00-531d-11e9-8bd6-8c0c69e23ed6.png)
