### ISSUE TITLE
Template.xml Startup Gate Location Being Ignored

### ISSUE THREAD

**Issue by Belickade** [ONElua/AdrenalineBubbleManager#95]
When adding a pre-made template.xml to my bubble images, the startup location's "style" is being ignored. I'm using the psmobile style to move the Startup Gate over to the right-hand side of the screen, but it stays at the default location (the center). I've tried installing my images/template multiple times, but it has only worked twice. 

I've tried editing the template.xml within the folder once the bubble is installed, but that doesn't seem to do anything (is the template being cached somewhere)?

The one bubble it did finally work on, I decided to uninstall it and try again. After reinstalling the same set of images/template, it went back to the default location.

I have tried this on multiple bubbles, and the result is the same (minus the 2 times it randomly worked).

**Comment by ONElua** [comment]
please share your template.xml

**Comment by Belickade** [comment]
Here is the template:

```
<?xml version="1.0" encoding="UTF-8"?>

-<livearea content-rev="1" format-ver="01.00" style="a5">


-<livearea-background>

<image>bg0.png</image>

</livearea-background>


-<gate>

<startup-image>startup.png</startup-image>

</gate>

</livearea>
```

Regardless of what I set the livearea style to, a5, psmobile etc, it reverts back to pspemu.

**Comment by ONElua** [comment]
please try this fix

https://www.dropbox.com/s/a89p9uf0j2407tj/AdrenalineBubbleManager.vpk?dl=0

**Comment by Belickade** [comment]
> please try this fix
> 
> https://www.dropbox.com/s/a89p9uf0j2407tj/AdrenalineBubbleManager.vpk?dl=0

Just tested this out, and it seems to be now working. I've only tested one bubble thus far, but it did recognize my template and properly place the startup gate according to the style I selected (a5 in this case). Out of curiosity, was anything major changed to make this work, or was there a minor bug that prevented it from working? Thanks for the change.

**Comment by ONElua** [comment]
Only my error :P

**Comment by ONElua** [comment]
now should working template.xml and frame 1 to frame 5

**Comment by Belickade** [comment]
Great, thanks for the changes. It really make using the app that much better!

**Comment by ONElua** [comment]
try more...
the next version
will be with these fix
