### ISSUE TITLE
[Feature request] Merging ABM & BubbleBooter

### ISSUE THREAD

**Issue by stuermera** [ONElua/AdrenalineBubbleManager#97]
Currently ABM only generates the nice Bubbles on the VITAs home menu - but an additional AdrenalineBubbleBooter is neccessary to allow them boot the games directly.

Merging those two, so only one app is needed would be great!

**Comment by ONElua** [comment]
I am taking its modules to facilitate the creation of bubbles from the same vita.
And its plugin adrbotter.suprx is from it, so ABM depends on Lman's updates.
