### ISSUE TITLE
AMB crash with C2-12828-1 after Vita keyboard shows

### ISSUE THREAD

**Issue by AzazelPL** [ONElua/AdrenalineBubbleManager#99]
- PSVITA model: PCH – 1000
- Version of firmware: 3.60 enso
- Version of ABM: 5.21
- Version of Adrenaline: 6.8

## After installing ABM and creating some bubbles

Obtained result: When i try to create more bubbles at once 3 and more I get C2-12828-1 after rename screen.
 
## Explain the issue

- I can make sometimes 2, sometimes 5 bubbles before it crach. Sometimes AMB freeze after rename game screen sometimes just after hiting X. Adrenaline works fine.

Update 1: this bug have something to do with game name changing. When I use default title option set to "yes" and vita keyboard not show, every thing works fine. I just made 25 bubbles without crash.

Update 2: on my second Vita every thing works fine. Same settings, ABM version and Adrenaline, same plugins and their order in config.txt. 

## Extra info

- reinstall adrenaline, and AMB
- sd2vita, and memory card
- Using tai:config.txt at ur0 
- yes I add the adrenaline line to tai:config.txt
- all ABM bubbles, random

**Comment by ONElua** [comment]
and what plugins do you have installed?

**Comment by AzazelPL** [comment]
*kernel
-gamesd
-nonpdrm
-repatch
-adrenaline_kernel
and shellbat under *main

**Comment by ONElua** [comment]
please uninstall all your bubbles ABM
please try this 
https://www.dropbox.com/s/a89p9uf0j2407tj/AdrenalineBubbleManager.vpk?dl=0

**Comment by AzazelPL** [comment]
I uninstalled all bubbles and install ABM from link but nothing changed.
Do i need to uninstall AMB first and then install again or i can install from the link on existing AMB?

**Comment by ONElua** [comment]
""Update 2: on my second Vita every thing works fine. Same settings, ABM version and Adrenaline, same plugins and their order in config.txt.""

I think it's SD2VITA problem
